# Generated by Django 4.2.21 on 2025-05-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceIntervalProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_interval_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('DEFINITION', 'Definition'), ('PROOF', 'Mathematical Proof'), ('EXAMPLE', 'Example'), ('EXPLANATION', 'Explanation'), ('INTERACTIVE', 'Interactive Element'), ('REFERENCE', 'Reference')], max_length=50)),
                ('category', models.CharField(choices=[('FOUNDATIONS', 'Theoretical Foundations'), ('METHODS', 'Statistical Methods'), ('APPLICATIONS', 'Applications'), ('INTERPRETATION', 'Interpretation'), ('OTHER', 'Other')], max_length=50)),
                ('content', models.TextField()),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='IntervalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('NORMAL', 'Normal'), ('BINOMIAL', 'Binomial'), ('POISSON', 'Poisson'), ('CUSTOM', 'Custom')], max_length=50)),
                ('data', models.JSONField()),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sets', to='confidence_intervals.confidenceintervalproject')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('simulation_type', models.CharField(choices=[('COVERAGE', 'Coverage Probability'), ('SAMPLE_SIZE', 'Sample Size Effects'), ('BOOTSTRAP_PERFORMANCE', 'Bootstrap Performance'), ('NON_NORMALITY', 'Effects of Non-normality'), ('BAYESIAN_COMPARISON', 'Frequentist vs Bayesian Comparison'), ('CUSTOM', 'Custom')], max_length=50)),
                ('parameters', models.JSONField()),
                ('results', models.JSONField()),
                ('visualization_settings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to='confidence_intervals.confidenceintervalproject')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('interval_type', models.CharField(choices=[('MEAN_Z', 'Mean (Z-interval, known variance)'), ('MEAN_T', 'Mean (T-interval, unknown variance)'), ('PROPORTION_WALD', 'Proportion (Wald)'), ('PROPORTION_WILSON', 'Proportion (Wilson)'), ('PROPORTION_CLOPPER_PEARSON', 'Proportion (Clopper-Pearson)'), ('VARIANCE', 'Variance'), ('STD_DEV', 'Standard Deviation'), ('DIFFERENCE_MEANS', 'Difference of Means'), ('DIFFERENCE_PROPORTIONS', 'Difference of Proportions'), ('BOOTSTRAP', 'Bootstrap'), ('BAYESIAN', 'Bayesian Credible Interval'), ('CUSTOM', 'Custom')], max_length=50)),
                ('confidence_level', models.FloatField()),
                ('parameters', models.JSONField()),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interval_results', to='confidence_intervals.intervaldata')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_results', to='confidence_intervals.confidenceintervalproject')),
            ],
        ),
    ]
