/**
 * Power Analysis Code Generator
 *
 * Generates reproducible R and Python code for power analysis calculations.
 * All generated code uses established statistical libraries and follows
 * best practices for reproducible research.
 *
 * R Libraries: pwr, WebPower, effectsize
 * Python Libraries: statsmodels, scipy, pingouin
 *
 * References:
 * - Cohen, J. (1988). Statistical power analysis for the behavioral sciences.
 * - Faul, F., et al. (2007). G*Power 3: A flexible statistical power analysis program.
 *
 * @module powerAnalysisCodeGenerator
 */

/**
 * Pitman asymptotic relative efficiency of a rank test against its parametric counterpart, by the
 * distribution the DATA are assumed to come from.
 *
 * Both rank-test generators used to hardcode `const are = 0.955` and tell the reader "for normally
 * distributed data" -- while the tool above them lets the user choose the parent distribution and
 * computes with the matching ARE. So a user who selected Laplace was shown n = 43 per group and
 * handed a script that computes 68. The exported code contradicted the analysis it claimed to
 * reproduce, which is worse than no script at all: it is the artifact that outlives the session.
 *
 * 3/π is also the WRONG default to fall back on silently. It is the efficiency under NORMALITY --
 * an odd assumption for a test chosen precisely because normality failed -- and the "~5% larger
 * samples" line it justified points the wrong way for every heavier-tailed parent, where the rank
 * test needs FEWER subjects, not more.
 *
 * Mirrors ARE_VS_PARAMETRIC in backend/core/hp_power_analysis_comprehensive.py.
 */
const ARE_BY_PARENT = {
  normal: 3 / Math.PI, // ~0.955
  uniform: 1.0,
  logistic: Math.PI ** 2 / 9, // ~1.097
  laplace: 1.5,
  exponential: 3.0,
};

const PARENT_LABEL = {
  normal: 'normal',
  uniform: 'uniform',
  logistic: 'logistic',
  laplace: 'Laplace (heavy-tailed)',
  exponential: 'exponential (skewed)',
};

/**
 * The ARE the displayed answer was actually computed with.
 *
 * Prefer the value the BACKEND returned: that is the one the number on screen came from, so the
 * script and the screen cannot disagree about the arithmetic.
 *
 * But only when it AGREES with the parent the script is about to name. `results` and
 * `parentDistribution` come from different places -- the former is the last completed run, the
 * latter is live UI state -- so a caller that lets them drift would have this function print
 *
 *     # This analysis assumes a Laplace (heavy-tailed) parent, ARE = 0.9549
 *
 * naming one distribution and computing with another, in a single line. (PowerAnalysisTool no
 * longer lets them drift -- it clears `results` when any input changes -- but a generator that is
 * only correct because its caller is careful is one refactor away from lying again, and this file
 * writes the artifact that outlives the session.)
 *
 * On disagreement the STATED parent wins, because that is what the surrounding prose commits to.
 */
const areFor = (results, parentDistribution) => {
  const table = ARE_BY_PARENT[parentDistribution] ?? ARE_BY_PARENT.normal;
  const fromBackend = results && results.are;

  if (typeof fromBackend !== 'number' || !Number.isFinite(fromBackend)) return table;

  // Same parent -> use the backend's value (it is the exact one the displayed answer used).
  // Different parent -> `results` is stale; the script must describe the parent it names.
  return Math.abs(fromBackend - table) < 1e-3 ? fromBackend : table;
};

/**
 * Generate R code for power analysis
 *
 * @param {Object} params - Analysis parameters
 * @param {string} params.testType - Type of statistical test
 * @param {string} params.calculationMode - 'power', 'sampleSize', or 'effectSize'
 * @param {number} params.alpha - Significance level
 * @param {number} params.power - Statistical power (1-β)
 * @param {number} params.effectSize - Effect size value
 * @param {number} params.sampleSize - Sample size (n)
 * @param {number} params.sampleSize2 - Sample size for group 2 (if applicable)
 * @param {number} params.numGroups - Number of groups (for ANOVA)
 * @param {string} params.alternative - 'two-sided', 'greater', or 'less'
 * @param {Object} params.results - Calculation results
 * @returns {string} R code
 */
export function generateRCode(params) {
  const {
    testType,
    calculationMode,
    alpha = 0.05,
    power = 0.80,
    effectSize = 0.5,
    sampleSize = 30,
    sampleSize2 = 30,
    numGroups = 3,
    alternative = 'two-sided',
    parentDistribution = 'normal',
    results = {}
  } = params;

  const timestamp = new Date().toISOString();
  const altR = alternative === 'two-sided' ? 'two.sided' : alternative;

  let code = `# ============================================================================
# Power Analysis - Generated by StickForStats
# ============================================================================
# Generated: ${timestamp}
# Test Type: ${getTestName(testType)}
# Calculation Mode: ${calculationMode}
#
# Scientific Foundation:
# - Cohen, J. (1988). Statistical power analysis for the behavioral sciences.
# - Faul, F., et al. (2007). G*Power 3: A flexible statistical power analysis program.
# ============================================================================

# Install required packages (run once)
# install.packages("pwr")
# install.packages("WebPower")  # For additional tests

# Load libraries
library(pwr)

`;

  // Generate test-specific code
  switch (testType) {
    case 'two-sample-t':
      code += generateRCodeTwoSampleT(calculationMode, alpha, power, effectSize, sampleSize, sampleSize2, altR, results);
      break;
    case 'one-sample-t':
      code += generateRCodeOneSampleT(calculationMode, alpha, power, effectSize, sampleSize, altR, results);
      break;
    case 'paired-t':
      code += generateRCodePairedT(calculationMode, alpha, power, effectSize, sampleSize, altR, results);
      break;
    case 'anova':
      code += generateRCodeANOVA(calculationMode, alpha, power, effectSize, sampleSize, numGroups, results);
      break;
    case 'correlation':
      code += generateRCodeCorrelation(calculationMode, alpha, power, effectSize, sampleSize, altR, results);
      break;
    case 'chi-square':
      code += generateRCodeChiSquare(calculationMode, alpha, power, effectSize, sampleSize, params.degreesOfFreedom || 1, results);
      break;
    case 'mann-whitney':
    case 'wilcoxon':
    case 'kruskal-wallis':
      code += generateRCodeNonParametric(testType, calculationMode, alpha, power, effectSize, sampleSize, numGroups, altR, results, parentDistribution);
      break;
    default:
      code += `# Test type "${testType}" code generation not yet implemented\n`;
  }

  code += `
# ============================================================================
# Interpretation Guide
# ============================================================================
# Cohen's Effect Size Benchmarks:
#   - Cohen's d (t-tests): Small=0.2, Medium=0.5, Large=0.8
#   - Cohen's f (ANOVA):   Small=0.10, Medium=0.25, Large=0.40
#   - Correlation r:       Small=0.10, Medium=0.30, Large=0.50
#   - Cohen's w (Chi-sq):  Small=0.10, Medium=0.30, Large=0.50
#
# Power Interpretation:
#   - 80% power is the conventional minimum for most research
#   - 90% power is recommended for clinical trials
#   - 95% power is used when Type II errors are costly
#
# Note: Power analysis should be conducted BEFORE data collection (a priori).
# Post-hoc power analysis is generally uninformative.
# ============================================================================
`;

  return code;
}

/**
 * Generate Python code for power analysis
 */
export function generatePythonCode(params) {
  const {
    testType,
    calculationMode,
    alpha = 0.05,
    power = 0.80,
    effectSize = 0.5,
    sampleSize = 30,
    sampleSize2 = 30,
    numGroups = 3,
    alternative = 'two-sided',
    parentDistribution = 'normal',
    results = {}
  } = params;

  const timestamp = new Date().toISOString();

  let code = `"""
============================================================================
Power Analysis - Generated by StickForStats
============================================================================
Generated: ${timestamp}
Test Type: ${getTestName(testType)}
Calculation Mode: ${calculationMode}

Scientific Foundation:
- Cohen, J. (1988). Statistical power analysis for the behavioral sciences.
- Faul, F., et al. (2007). G*Power 3: A flexible statistical power analysis program.
============================================================================
"""

# Install required packages (run once in terminal):
# pip install statsmodels scipy pingouin

import numpy as np
from scipy import stats
from statsmodels.stats.power import (
    TTestIndPower,
    TTestPower,
    FTestAnovaPower,
    GofChisquarePower,
    NormalIndPower
)

`;

  // Generate test-specific code
  switch (testType) {
    case 'two-sample-t':
      code += generatePythonCodeTwoSampleT(calculationMode, alpha, power, effectSize, sampleSize, sampleSize2, alternative, results);
      break;
    case 'one-sample-t':
      code += generatePythonCodeOneSampleT(calculationMode, alpha, power, effectSize, sampleSize, alternative, results);
      break;
    case 'paired-t':
      code += generatePythonCodePairedT(calculationMode, alpha, power, effectSize, sampleSize, alternative, results);
      break;
    case 'anova':
      code += generatePythonCodeANOVA(calculationMode, alpha, power, effectSize, sampleSize, numGroups, results);
      break;
    case 'correlation':
      code += generatePythonCodeCorrelation(calculationMode, alpha, power, effectSize, sampleSize, alternative, results);
      break;
    case 'chi-square':
      code += generatePythonCodeChiSquare(calculationMode, alpha, power, effectSize, sampleSize, params.degreesOfFreedom || 1, results);
      break;
    case 'mann-whitney':
    case 'wilcoxon':
    case 'kruskal-wallis':
      code += generatePythonCodeNonParametric(testType, calculationMode, alpha, power, effectSize, sampleSize, numGroups, alternative, results, parentDistribution);
      break;
    default:
      code += `# Test type "${testType}" code generation not yet implemented\n`;
  }

  code += `
# ============================================================================
# Interpretation Guide
# ============================================================================
# Cohen's Effect Size Benchmarks:
#   - Cohen's d (t-tests): Small=0.2, Medium=0.5, Large=0.8
#   - Cohen's f (ANOVA):   Small=0.10, Medium=0.25, Large=0.40
#   - Correlation r:       Small=0.10, Medium=0.30, Large=0.50
#   - Cohen's w (Chi-sq):  Small=0.10, Medium=0.30, Large=0.50
#
# Power Interpretation:
#   - 80% power is the conventional minimum for most research
#   - 90% power is recommended for clinical trials
#   - 95% power is used when Type II errors are costly
#
# Note: Power analysis should be conducted BEFORE data collection (a priori).
# Post-hoc power analysis is generally uninformative.
# ============================================================================
`;

  return code;
}

// ============================================================================
// R Code Generators for Specific Tests
// ============================================================================

function generateRCodeTwoSampleT(mode, alpha, power, d, n1, n2, alt, results) {
  const ratio = n2 / n1;

  if (mode === 'power') {
    return `# Two-Sample Independent t-test: Calculate Power
# Parameters
d <- ${d}        # Cohen's d effect size
n1 <- ${n1}      # Sample size group 1
n2 <- ${n2}      # Sample size group 2
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

# Calculate power using pwr package
# Note: pwr.t2n.test handles unequal sample sizes
result <- pwr.t2n.test(
  n1 = n1,
  n2 = n2,
  d = d,
  sig.level = alpha,
  alternative = alternative
)

# Display results
print(result)
cat("\\n")
cat("Achieved Power:", round(result$power * 100, 2), "%\\n")
cat("Effect Size (Cohen's d):", d, "\\n")
cat("Total Sample Size:", n1 + n2, "\\n")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# Two-Sample Independent t-test: Calculate Sample Size
# Parameters
d <- ${d}        # Cohen's d effect size
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

# Calculate required sample size
result <- pwr.t.test(
  d = d,
  power = power,
  sig.level = alpha,
  type = "two.sample",
  alternative = alternative
)

# Display results
print(result)
cat("\\n")
cat("Required n per group:", ceiling(result$n), "\\n")
cat("Total sample size:", ceiling(result$n) * 2, "\\n")

# For unequal allocation (ratio = ${ratio}):
# n1 = ceiling(result$n)
# n2 = ceiling(result$n * ${ratio})

# StickForStats Result: n = ${results.totalN || results.n1 + results.n2 || 'N/A'}
`;
  } else {
    return `# Two-Sample Independent t-test: Calculate Minimum Detectable Effect Size
# Parameters
n1 <- ${n1}      # Sample size group 1
n2 <- ${n2}      # Sample size group 2
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

# Calculate minimum detectable effect size
# Using pwr.t2n.test with n specified, solving for d
result <- pwr.t2n.test(
  n1 = n1,
  n2 = n2,
  power = power,
  sig.level = alpha,
  alternative = alternative
)

# Display results
print(result)
cat("\\n")
cat("Minimum Detectable Effect Size (Cohen's d):", round(result$d, 4), "\\n")

# StickForStats Result: d = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generateRCodeOneSampleT(mode, alpha, power, d, n, alt, results) {
  if (mode === 'power') {
    return `# One-Sample t-test: Calculate Power
# Parameters
d <- ${d}        # Cohen's d effect size
n <- ${n}        # Sample size
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

# Calculate power
result <- pwr.t.test(
  n = n,
  d = d,
  sig.level = alpha,
  type = "one.sample",
  alternative = alternative
)

print(result)
cat("\\nAchieved Power:", round(result$power * 100, 2), "%\\n")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# One-Sample t-test: Calculate Sample Size
# Parameters
d <- ${d}        # Cohen's d effect size
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

result <- pwr.t.test(
  d = d,
  power = power,
  sig.level = alpha,
  type = "one.sample",
  alternative = alternative
)

print(result)
cat("\\nRequired Sample Size:", ceiling(result$n), "\\n")

# StickForStats Result: n = ${results.n || results.totalN || 'N/A'}
`;
  } else {
    return `# One-Sample t-test: Calculate Minimum Detectable Effect Size
# Parameters
n <- ${n}        # Sample size
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

result <- pwr.t.test(
  n = n,
  power = power,
  sig.level = alpha,
  type = "one.sample",
  alternative = alternative
)

print(result)
cat("\\nMinimum Detectable Effect Size:", round(result$d, 4), "\\n")

# StickForStats Result: d = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generateRCodePairedT(mode, alpha, power, d, n, alt, results) {
  if (mode === 'power') {
    return `# Paired t-test: Calculate Power
# Parameters
d <- ${d}        # Cohen's d effect size (for paired differences)
n <- ${n}        # Number of pairs
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

# Calculate power
result <- pwr.t.test(
  n = n,
  d = d,
  sig.level = alpha,
  type = "paired",
  alternative = alternative
)

print(result)
cat("\\nAchieved Power:", round(result$power * 100, 2), "%\\n")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# Paired t-test: Calculate Sample Size
# Parameters
d <- ${d}        # Cohen's d effect size
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

result <- pwr.t.test(
  d = d,
  power = power,
  sig.level = alpha,
  type = "paired",
  alternative = alternative
)

print(result)
cat("\\nRequired Number of Pairs:", ceiling(result$n), "\\n")

# StickForStats Result: n = ${results.n || results.totalN || 'N/A'}
`;
  } else {
    return `# Paired t-test: Calculate Minimum Detectable Effect Size
# Parameters
n <- ${n}        # Number of pairs
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

result <- pwr.t.test(
  n = n,
  power = power,
  sig.level = alpha,
  type = "paired",
  alternative = alternative
)

print(result)
cat("\\nMinimum Detectable Effect Size:", round(result$d, 4), "\\n")

# StickForStats Result: d = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generateRCodeANOVA(mode, alpha, power, f, n, k, results) {
  if (mode === 'power') {
    return `# One-Way ANOVA: Calculate Power
# Parameters
f <- ${f}        # Cohen's f effect size
n <- ${n}        # Sample size per group
k <- ${k}        # Number of groups
alpha <- ${alpha}  # Significance level

# Calculate power using pwr.anova.test
result <- pwr.anova.test(
  k = k,
  n = n,
  f = f,
  sig.level = alpha
)

print(result)
cat("\\nAchieved Power:", round(result$power * 100, 2), "%\\n")
cat("Total Sample Size:", n * k, "\\n")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# One-Way ANOVA: Calculate Sample Size
# Parameters
f <- ${f}        # Cohen's f effect size
k <- ${k}        # Number of groups
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level

result <- pwr.anova.test(
  k = k,
  f = f,
  power = power,
  sig.level = alpha
)

print(result)
cat("\\nRequired n per group:", ceiling(result$n), "\\n")
cat("Total sample size:", ceiling(result$n) * k, "\\n")

# StickForStats Result: n = ${results.totalN || (results.nPerGroup * k) || 'N/A'}
`;
  } else {
    return `# One-Way ANOVA: Calculate Minimum Detectable Effect Size
# Parameters
n <- ${n}        # Sample size per group
k <- ${k}        # Number of groups
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level

result <- pwr.anova.test(
  k = k,
  n = n,
  power = power,
  sig.level = alpha
)

print(result)
cat("\\nMinimum Detectable Effect Size (Cohen's f):", round(result$f, 4), "\\n")

# StickForStats Result: f = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generateRCodeCorrelation(mode, alpha, power, r, n, alt, results) {
  if (mode === 'power') {
    return `# Correlation Test: Calculate Power
# Parameters
r <- ${r}        # Expected correlation
n <- ${n}        # Sample size
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

# Calculate power using pwr.r.test
result <- pwr.r.test(
  n = n,
  r = r,
  sig.level = alpha,
  alternative = alternative
)

print(result)
cat("\\nAchieved Power:", round(result$power * 100, 2), "%\\n")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# Correlation Test: Calculate Sample Size
# Parameters
r <- ${r}        # Expected correlation
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

result <- pwr.r.test(
  r = r,
  power = power,
  sig.level = alpha,
  alternative = alternative
)

print(result)
cat("\\nRequired Sample Size:", ceiling(result$n), "\\n")

# StickForStats Result: n = ${results.n || results.totalN || 'N/A'}
`;
  } else {
    return `# Correlation Test: Calculate Minimum Detectable Effect Size
# Parameters
n <- ${n}        # Sample size
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level
alternative <- "${alt}"

result <- pwr.r.test(
  n = n,
  power = power,
  sig.level = alpha,
  alternative = alternative
)

print(result)
cat("\\nMinimum Detectable Correlation:", round(result$r, 4), "\\n")

# StickForStats Result: r = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generateRCodeChiSquare(mode, alpha, power, w, n, df, results) {
  if (mode === 'power') {
    return `# Chi-Square Test: Calculate Power
# Parameters
w <- ${w}        # Cohen's w effect size
n <- ${n}        # Total sample size
df <- ${df}      # Degrees of freedom
alpha <- ${alpha}  # Significance level

# Calculate power using pwr.chisq.test
result <- pwr.chisq.test(
  N = n,
  w = w,
  df = df,
  sig.level = alpha
)

print(result)
cat("\\nAchieved Power:", round(result$power * 100, 2), "%\\n")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# Chi-Square Test: Calculate Sample Size
# Parameters
w <- ${w}        # Cohen's w effect size
df <- ${df}      # Degrees of freedom
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level

result <- pwr.chisq.test(
  w = w,
  df = df,
  power = power,
  sig.level = alpha
)

print(result)
cat("\\nRequired Sample Size:", ceiling(result$N), "\\n")

# StickForStats Result: n = ${results.n || results.totalN || 'N/A'}
`;
  } else {
    return `# Chi-Square Test: Calculate Minimum Detectable Effect Size
# Parameters
n <- ${n}        # Total sample size
df <- ${df}      # Degrees of freedom
power <- ${power}  # Desired power
alpha <- ${alpha}  # Significance level

result <- pwr.chisq.test(
  N = n,
  df = df,
  power = power,
  sig.level = alpha
)

print(result)
cat("\\nMinimum Detectable Effect Size (Cohen's w):", round(result$w, 4), "\\n")

# StickForStats Result: w = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generateRCodeNonParametric(testType, mode, alpha, power, d, n, k, alt, results, parentDistribution = 'normal') {
  const testName = getTestName(testType);
  const are = areFor(results, parentDistribution);

  return `# ${testName}: Power Analysis
# ============================================================================
# Non-parametric tests have no distribution-free closed-form power. This uses the Pitman
# asymptotic relative efficiency (ARE) of the rank test against its parametric counterpart:
# the rank test at n behaves like the parametric test at n * ARE.
#
# THE ARE DEPENDS ON THE DISTRIBUTION THE DATA COME FROM, and the answer is not a footnote:
#
#     parent distribution      ARE     n per group (d = 0.5, 80% power)
#     ---------------------  ------    --------------------------------
#     normal                  0.955                  68
#     uniform                 1.000                  64
#     logistic                1.097                  59
#     Laplace (heavy tails)   1.500                  43
#     exponential (skewed)    3.000                  22
#
# This analysis assumes a ${PARENT_LABEL[parentDistribution] || parentDistribution} parent, ARE = ${are.toFixed(4)}.
#
# Note that ARE = 3/pi ~ 0.955 -- the figure usually quoted, and the source of the common claim
# that rank tests "cost about 5% more subjects" -- holds only under NORMALITY, which is an odd
# thing to assume about data for which you have chosen a rank test. For every heavier-tailed
# parent the ARE is ABOVE 1 and the rank test needs FEWER subjects, not more.
# ============================================================================

# Parameters
d <- ${d}        # Effect size (Cohen's d equivalent)
n <- ${n}        # Sample size
alpha <- ${alpha}  # Significance level
ARE <- ${are.toFixed(6)}     # Pitman ARE, ${PARENT_LABEL[parentDistribution] || parentDistribution} parent

# Approach: Calculate power for parametric equivalent, then adjust
# The effective sample size for non-parametric is n * ARE

effective_n <- n * ARE

${testType === 'mann-whitney' ? `
# Mann-Whitney U is equivalent to independent t-test
# Use t-test power with effective sample size
result <- pwr.t.test(
  n = effective_n,
  d = d,
  sig.level = alpha,
  type = "two.sample",
  alternative = "${alt}"
)
` : testType === 'wilcoxon' ? `
# Wilcoxon Signed-Rank is equivalent to paired t-test
result <- pwr.t.test(
  n = effective_n,
  d = d,
  sig.level = alpha,
  type = "paired",
  alternative = "${alt}"
)
` : `
# Kruskal-Wallis is equivalent to one-way ANOVA
result <- pwr.anova.test(
  k = ${k},
  n = effective_n,
  f = d,  # Using Cohen's f for ANOVA
  sig.level = alpha
)
`}

print(result)
cat("\\n")
cat("Note: Power adjusted for ARE =", ARE, "\\n")
cat("Effective sample size:", round(effective_n, 1), "\\n")

# For the EXACT required sample size for non-parametric test:
# n_nonparametric = ceiling(n_parametric / ARE)

# StickForStats Result: ${results.power ? 'Power = ' + (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
}

// ============================================================================
// Python Code Generators for Specific Tests
// ============================================================================

function generatePythonCodeTwoSampleT(mode, alpha, power, d, n1, n2, alt, results) {
  const altPy = alt === 'two-sided' ? 'two-sided' : alt === 'greater' ? 'larger' : 'smaller';

  if (mode === 'power') {
    return `# Two-Sample Independent t-test: Calculate Power
# Parameters
d = ${d}        # Cohen's d effect size
n1 = ${n1}      # Sample size group 1
n2 = ${n2}      # Sample size group 2
alpha = ${alpha}  # Significance level
alternative = "${altPy}"

# Calculate power using statsmodels
analysis = TTestIndPower()

# For equal sample sizes, use ratio=1
ratio = n2 / n1
power_result = analysis.power(
    effect_size=d,
    nobs1=n1,
    ratio=ratio,
    alpha=alpha,
    alternative=alternative
)

print(f"Two-Sample t-test Power Analysis")
print(f"=" * 40)
print(f"Effect Size (Cohen's d): {d}")
print(f"Sample Size Group 1: {n1}")
print(f"Sample Size Group 2: {n2}")
print(f"Significance Level: {alpha}")
print(f"Alternative: {alternative}")
print(f"-" * 40)
print(f"Achieved Power: {power_result:.4f} ({power_result*100:.2f}%)")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# Two-Sample Independent t-test: Calculate Sample Size
# Parameters
d = ${d}        # Cohen's d effect size
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level
alternative = "${altPy}"

# Calculate required sample size
analysis = TTestIndPower()
n = analysis.solve_power(
    effect_size=d,
    power=power_target,
    alpha=alpha,
    ratio=1.0,  # Equal allocation
    alternative=alternative
)

import math
n_per_group = math.ceil(n)
total_n = n_per_group * 2

print(f"Two-Sample t-test Sample Size Calculation")
print(f"=" * 40)
print(f"Effect Size (Cohen's d): {d}")
print(f"Target Power: {power_target}")
print(f"Significance Level: {alpha}")
print(f"-" * 40)
print(f"Required n per group: {n_per_group}")
print(f"Total sample size: {total_n}")

# StickForStats Result: n = ${results.totalN || results.n1 + results.n2 || 'N/A'}
`;
  } else {
    return `# Two-Sample Independent t-test: Calculate Minimum Detectable Effect Size
# Parameters
n = ${n1}         # Sample size per group
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level
alternative = "${altPy}"

# Calculate minimum detectable effect size
analysis = TTestIndPower()
d = analysis.solve_power(
    nobs1=n,
    power=power_target,
    alpha=alpha,
    ratio=1.0,
    alternative=alternative
)

print(f"Two-Sample t-test Effect Size Calculation")
print(f"=" * 40)
print(f"Sample Size per group: {n}")
print(f"Target Power: {power_target}")
print(f"Significance Level: {alpha}")
print(f"-" * 40)
print(f"Minimum Detectable Effect Size (Cohen's d): {d:.4f}")

# StickForStats Result: d = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generatePythonCodeOneSampleT(mode, alpha, power, d, n, alt, results) {
  const altPy = alt === 'two-sided' ? 'two-sided' : alt === 'greater' ? 'larger' : 'smaller';

  if (mode === 'power') {
    return `# One-Sample t-test: Calculate Power
# Parameters
d = ${d}        # Cohen's d effect size
n = ${n}        # Sample size
alpha = ${alpha}  # Significance level
alternative = "${altPy}"

# Calculate power
analysis = TTestPower()
power_result = analysis.power(
    effect_size=d,
    nobs=n,
    alpha=alpha,
    alternative=alternative
)

print(f"One-Sample t-test Power Analysis")
print(f"=" * 40)
print(f"Effect Size (Cohen's d): {d}")
print(f"Sample Size: {n}")
print(f"Significance Level: {alpha}")
print(f"-" * 40)
print(f"Achieved Power: {power_result:.4f} ({power_result*100:.2f}%)")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# One-Sample t-test: Calculate Sample Size
# Parameters
d = ${d}        # Cohen's d effect size
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level
alternative = "${altPy}"

analysis = TTestPower()
n = analysis.solve_power(
    effect_size=d,
    power=power_target,
    alpha=alpha,
    alternative=alternative
)

import math
n_required = math.ceil(n)

print(f"One-Sample t-test Sample Size Calculation")
print(f"=" * 40)
print(f"Effect Size (Cohen's d): {d}")
print(f"Target Power: {power_target}")
print(f"-" * 40)
print(f"Required Sample Size: {n_required}")

# StickForStats Result: n = ${results.n || results.totalN || 'N/A'}
`;
  } else {
    return `# One-Sample t-test: Calculate Minimum Detectable Effect Size
# Parameters
n = ${n}          # Sample size
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level
alternative = "${altPy}"

analysis = TTestPower()
d = analysis.solve_power(
    nobs=n,
    power=power_target,
    alpha=alpha,
    alternative=alternative
)

print(f"One-Sample t-test Effect Size Calculation")
print(f"=" * 40)
print(f"Sample Size: {n}")
print(f"Target Power: {power_target}")
print(f"-" * 40)
print(f"Minimum Detectable Effect Size: {d:.4f}")

# StickForStats Result: d = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generatePythonCodePairedT(mode, alpha, power, d, n, alt, results) {
  // Paired t-test uses TTestPower (same as one-sample)
  return generatePythonCodeOneSampleT(mode, alpha, power, d, n, alt, results)
    .replace(/One-Sample/g, 'Paired')
    .replace(/Sample Size/g, 'Number of Pairs');
}

function generatePythonCodeANOVA(mode, alpha, power, f, n, k, results) {
  if (mode === 'power') {
    return `# One-Way ANOVA: Calculate Power
# Parameters
f = ${f}        # Cohen's f effect size
n = ${n}        # Sample size per group
k = ${k}        # Number of groups
alpha = ${alpha}  # Significance level

# Calculate power using FTestAnovaPower
analysis = FTestAnovaPower()

# Note: effect_size in statsmodels is Cohen's f
power_result = analysis.power(
    effect_size=f,
    nobs=n * k,  # Total sample size
    alpha=alpha,
    k_groups=k
)

print(f"One-Way ANOVA Power Analysis")
print(f"=" * 40)
print(f"Effect Size (Cohen's f): {f}")
print(f"Sample Size per group: {n}")
print(f"Number of groups: {k}")
print(f"Total sample size: {n * k}")
print(f"-" * 40)
print(f"Achieved Power: {power_result:.4f} ({power_result*100:.2f}%)")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# One-Way ANOVA: Calculate Sample Size
# Parameters
f = ${f}        # Cohen's f effect size
k = ${k}        # Number of groups
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level

analysis = FTestAnovaPower()
total_n = analysis.solve_power(
    effect_size=f,
    power=power_target,
    alpha=alpha,
    k_groups=k
)

import math
n_per_group = math.ceil(total_n / k)
total_sample = n_per_group * k

print(f"One-Way ANOVA Sample Size Calculation")
print(f"=" * 40)
print(f"Effect Size (Cohen's f): {f}")
print(f"Number of groups: {k}")
print(f"Target Power: {power_target}")
print(f"-" * 40)
print(f"Required n per group: {n_per_group}")
print(f"Total sample size: {total_sample}")

# StickForStats Result: n = ${results.totalN || (results.nPerGroup * k) || 'N/A'}
`;
  } else {
    return `# One-Way ANOVA: Calculate Minimum Detectable Effect Size
# Parameters
n = ${n}        # Sample size per group
k = ${k}        # Number of groups
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level

analysis = FTestAnovaPower()
f = analysis.solve_power(
    nobs=n * k,
    power=power_target,
    alpha=alpha,
    k_groups=k
)

print(f"One-Way ANOVA Effect Size Calculation")
print(f"=" * 40)
print(f"Sample Size per group: {n}")
print(f"Number of groups: {k}")
print(f"Target Power: {power_target}")
print(f"-" * 40)
print(f"Minimum Detectable Effect Size (Cohen's f): {f:.4f}")

# StickForStats Result: f = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generatePythonCodeCorrelation(mode, alpha, power, r, n, alt, results) {
  const altPy = alt === 'two-sided' ? 'two-sided' : alt === 'greater' ? 'larger' : 'smaller';

  return `# Correlation Test: Power Analysis
# ============================================================================
# Using Fisher's z transformation for correlation power analysis
# ============================================================================
from scipy.stats import norm
import math

# Parameters
r = ${r}         # Expected correlation
n = ${n}         # Sample size
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level
alternative = "${altPy}"

# Fisher's z transformation
def fisher_z(r):
    return 0.5 * math.log((1 + r) / (1 - r))

# Standard error of Fisher's z
def fisher_se(n):
    return 1 / math.sqrt(n - 3)

${mode === 'power' ? `
# Calculate power
z_r = fisher_z(r)
se = fisher_se(n)

if alternative == "two-sided":
    z_crit = norm.ppf(1 - alpha / 2)
    power_result = norm.cdf(z_r / se - z_crit) + norm.cdf(-z_r / se - z_crit)
else:
    z_crit = norm.ppf(1 - alpha)
    power_result = norm.cdf(z_r / se - z_crit)

print(f"Correlation Power Analysis")
print(f"=" * 40)
print(f"Expected Correlation: {r}")
print(f"Sample Size: {n}")
print(f"Fisher's z: {z_r:.4f}")
print(f"-" * 40)
print(f"Achieved Power: {power_result:.4f} ({power_result*100:.2f}%)")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
` : mode === 'sampleSize' ? `
# Calculate sample size
z_r = fisher_z(r)
z_alpha = norm.ppf(1 - alpha / 2) if alternative == "two-sided" else norm.ppf(1 - alpha)
z_beta = norm.ppf(power_target)

n_required = math.ceil(((z_alpha + z_beta) / z_r) ** 2 + 3)

print(f"Correlation Sample Size Calculation")
print(f"=" * 40)
print(f"Expected Correlation: {r}")
print(f"Target Power: {power_target}")
print(f"-" * 40)
print(f"Required Sample Size: {n_required}")

# StickForStats Result: n = ${results.n || results.totalN || 'N/A'}
` : `
# Calculate minimum detectable correlation
# Binary search for effect size
def calc_power_for_r(r_test, n, alpha, alternative):
    z_r = fisher_z(r_test)
    se = fisher_se(n)
    if alternative == "two-sided":
        z_crit = norm.ppf(1 - alpha / 2)
        return norm.cdf(z_r / se - z_crit) + norm.cdf(-z_r / se - z_crit)
    else:
        z_crit = norm.ppf(1 - alpha)
        return norm.cdf(z_r / se - z_crit)

r_min, r_max = 0.01, 0.99
while r_max - r_min > 0.001:
    r_mid = (r_min + r_max) / 2
    power_at_mid = calc_power_for_r(r_mid, n, alpha, alternative)
    if power_at_mid < power_target:
        r_min = r_mid
    else:
        r_max = r_mid

min_r = (r_min + r_max) / 2

print(f"Correlation Effect Size Calculation")
print(f"=" * 40)
print(f"Sample Size: {n}")
print(f"Target Power: {power_target}")
print(f"-" * 40)
print(f"Minimum Detectable Correlation: {min_r:.4f}")

# StickForStats Result: r = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`}
`;
}

function generatePythonCodeChiSquare(mode, alpha, power, w, n, df, results) {
  if (mode === 'power') {
    return `# Chi-Square Test: Calculate Power
# Parameters
w = ${w}        # Cohen's w effect size
n = ${n}        # Total sample size
df = ${df}      # Degrees of freedom
alpha = ${alpha}  # Significance level

# Calculate power using GofChisquarePower
analysis = GofChisquarePower()
power_result = analysis.power(
    effect_size=w,
    nobs=n,
    n_bins=df + 1,  # n_bins = df + 1
    alpha=alpha
)

print(f"Chi-Square Test Power Analysis")
print(f"=" * 40)
print(f"Effect Size (Cohen's w): {w}")
print(f"Sample Size: {n}")
print(f"Degrees of Freedom: {df}")
print(f"-" * 40)
print(f"Achieved Power: {power_result:.4f} ({power_result*100:.2f}%)")

# StickForStats Result: ${results.power ? (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
  } else if (mode === 'sampleSize') {
    return `# Chi-Square Test: Calculate Sample Size
# Parameters
w = ${w}        # Cohen's w effect size
df = ${df}      # Degrees of freedom
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level

analysis = GofChisquarePower()
n = analysis.solve_power(
    effect_size=w,
    power=power_target,
    n_bins=df + 1,
    alpha=alpha
)

import math
n_required = math.ceil(n)

print(f"Chi-Square Test Sample Size Calculation")
print(f"=" * 40)
print(f"Effect Size (Cohen's w): {w}")
print(f"Degrees of Freedom: {df}")
print(f"Target Power: {power_target}")
print(f"-" * 40)
print(f"Required Sample Size: {n_required}")

# StickForStats Result: n = ${results.n || results.totalN || 'N/A'}
`;
  } else {
    return `# Chi-Square Test: Calculate Minimum Detectable Effect Size
# Parameters
n = ${n}        # Total sample size
df = ${df}      # Degrees of freedom
power_target = ${power}  # Desired power
alpha = ${alpha}  # Significance level

analysis = GofChisquarePower()
w = analysis.solve_power(
    nobs=n,
    power=power_target,
    n_bins=df + 1,
    alpha=alpha
)

print(f"Chi-Square Test Effect Size Calculation")
print(f"=" * 40)
print(f"Sample Size: {n}")
print(f"Degrees of Freedom: {df}")
print(f"Target Power: {power_target}")
print(f"-" * 40)
print(f"Minimum Detectable Effect Size (Cohen's w): {w:.4f}")

# StickForStats Result: w = ${results.effectSize ? results.effectSize.toFixed(4) : 'N/A'}
`;
  }
}

function generatePythonCodeNonParametric(testType, mode, alpha, power, d, n, k, alt, results, parentDistribution = 'normal') {
  const testName = getTestName(testType);
  const are = areFor(results, parentDistribution);

  return `# ${testName}: Power Analysis
# ============================================================================
# Non-parametric tests have no distribution-free closed-form power. This uses the Pitman
# asymptotic relative efficiency (ARE) of the rank test against its parametric counterpart:
# the rank test at n behaves like the parametric test at n * ARE.
#
# THE ARE DEPENDS ON THE DISTRIBUTION THE DATA COME FROM, and the answer is not a footnote:
#
#     parent distribution      ARE     n per group (d = 0.5, 80% power)
#     ---------------------  ------    --------------------------------
#     normal                  0.955                  68
#     uniform                 1.000                  64
#     logistic                1.097                  59
#     Laplace (heavy tails)   1.500                  43
#     exponential (skewed)    3.000                  22
#
# This analysis assumes a ${PARENT_LABEL[parentDistribution] || parentDistribution} parent, ARE = ${are.toFixed(4)}.
#
# Note that ARE = 3/pi ~ 0.955 -- the figure usually quoted, and the source of the common claim
# that rank tests "cost about 5% more subjects" -- holds only under NORMALITY, which is an odd
# thing to assume about data for which you have chosen a rank test. For every heavier-tailed
# parent the ARE is ABOVE 1 and the rank test needs FEWER subjects, not more.
# ============================================================================

# Parameters
d = ${d}        # Effect size (Cohen's d equivalent)
n = ${n}        # Sample size
alpha = ${alpha}  # Significance level
ARE = ${are.toFixed(6)}     # Pitman ARE, ${PARENT_LABEL[parentDistribution] || parentDistribution} parent

# Effective sample size for non-parametric is n * ARE
effective_n = n * ARE

${testType === 'mann-whitney' ? `
# Mann-Whitney U is equivalent to independent t-test
analysis = TTestIndPower()
power_result = analysis.power(
    effect_size=d,
    nobs1=int(effective_n),
    ratio=1.0,
    alpha=alpha,
    alternative="two-sided"
)
` : testType === 'wilcoxon' ? `
# Wilcoxon Signed-Rank is equivalent to paired t-test
analysis = TTestPower()
power_result = analysis.power(
    effect_size=d,
    nobs=int(effective_n),
    alpha=alpha,
    alternative="two-sided"
)
` : `
# Kruskal-Wallis is equivalent to one-way ANOVA
k = ${k}
analysis = FTestAnovaPower()
power_result = analysis.power(
    effect_size=d,
    nobs=int(effective_n * k),
    alpha=alpha,
    k_groups=k
)
`}

print(f"${testName} Power Analysis")
print(f"=" * 40)
print(f"Effect Size: {d}")
print(f"Original Sample Size: {n}")
print(f"Effective Sample Size (ARE adjusted): {effective_n:.1f}")
print(f"ARE: {ARE}")
print(f"-" * 40)
print(f"Approximate Power: {power_result:.4f} ({power_result*100:.2f}%)")

# For exact sample size needed for non-parametric:
# n_nonparametric = ceil(n_parametric / ARE)

# StickForStats Result: ${results.power ? 'Power = ' + (results.power * 100).toFixed(2) + '%' : 'N/A'}
`;
}

// ============================================================================
// Helper Functions
// ============================================================================

function getTestName(testType) {
  const names = {
    'two-sample-t': 'Two-Sample Independent t-test',
    'one-sample-t': 'One-Sample t-test',
    'paired-t': 'Paired t-test',
    'anova': 'One-Way ANOVA',
    'correlation': 'Correlation Test',
    'chi-square': 'Chi-Square Test',
    'mann-whitney': 'Mann-Whitney U Test',
    'wilcoxon': 'Wilcoxon Signed-Rank Test',
    'kruskal-wallis': 'Kruskal-Wallis Test'
  };
  return names[testType] || testType;
}

/**
 * Download code as a file
 *
 * @param {string} code - The code to download
 * @param {string} language - 'R' or 'Python'
 * @param {string} testType - Type of test for filename
 */
export function downloadCode(code, language, testType) {
  const extension = language === 'R' ? 'R' : 'py';
  const filename = `power_analysis_${testType}_${new Date().toISOString().split('T')[0]}.${extension}`;

  const blob = new Blob([code], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Copy code to clipboard
 *
 * @param {string} code - The code to copy
 * @returns {Promise<boolean>} Success status
 */
export async function copyToClipboard(code) {
  try {
    await navigator.clipboard.writeText(code);
    return true;
  } catch (err) {
    console.error('Failed to copy:', err);
    return false;
  }
}

const powerAnalysisCodeGenerator = {
  generateRCode,
  generatePythonCode,
  downloadCode,
  copyToClipboard
};

export default powerAnalysisCodeGenerator;
