/**
 * Statistical Tests Code Generator
 *
 * Generates reproducible R and Python code for statistical analyses with data.
 * Includes Guardian assumption checks for scientific integrity.
 *
 * Coverage:
 * - Parametric tests (t-tests, ANOVA, correlation, regression)
 * - Non-parametric tests (Mann-Whitney, Kruskal-Wallis, Wilcoxon, etc.)
 * - Categorical tests (Chi-square, Fisher's exact, McNemar's)
 * - Assumption checks (normality, homogeneity, independence)
 * - Effect size calculations
 * - Descriptive statistics
 *
 * R Libraries: stats, car, effectsize, nortest, lawstat
 * Python Libraries: scipy, statsmodels, pingouin, pandas, numpy
 *
 * Scientific Foundation:
 * - Cohen, J. (1988). Statistical power analysis for the behavioral sciences.
 * - Field, A. (2018). Discovering statistics using IBM SPSS statistics.
 * - Wilcox, R. (2017). Introduction to robust estimation and hypothesis testing.
 *
 * @module statisticalTestsCodeGenerator
 */

// ============================================================================
// MAIN EXPORT FUNCTIONS
// ============================================================================

/**
 * Generate complete R code for a statistical test with data
 *
 * @param {Object} params - Test parameters
 * @param {string} params.testType - Type of statistical test
 * @param {Array} params.data - Data arrays
 * @param {Object} params.results - Test results from StickForStats
 * @param {Object} params.assumptions - Guardian assumption check results
 * @param {Object} params.options - Test options (alpha, alternative, etc.)
 * @returns {string} Complete R code
 */
export function generateRCode(params) {
  const {
    testType,
    data = {},
    results = {},
    assumptions = {},
    options = {}
  } = params;

  const timestamp = new Date().toISOString();
  const testName = getTestName(testType);

  let code = generateRHeader(timestamp, testName, options);
  code += generateRDataSection(data, testType);
  code += generateRAssumptionChecks(testType, assumptions);
  code += generateRTestCode(testType, data, options, results);
  code += generateREffectSize(testType, results);
  code += generateRInterpretation(testType, results);
  code += generateRFooter(testType);

  return code;
}

/**
 * Generate complete Python code for a statistical test with data
 */
export function generatePythonCode(params) {
  const {
    testType,
    data = {},
    results = {},
    assumptions = {},
    options = {}
  } = params;

  const timestamp = new Date().toISOString();
  const testName = getTestName(testType);

  let code = generatePythonHeader(timestamp, testName, options);
  code += generatePythonDataSection(data, testType);
  code += generatePythonAssumptionChecks(testType, assumptions);
  code += generatePythonTestCode(testType, data, options, results);
  code += generatePythonEffectSize(testType, results);
  code += generatePythonInterpretation(testType, results);
  code += generatePythonFooter(testType);

  return code;
}

// ============================================================================
// R CODE GENERATION SECTIONS
// ============================================================================

function generateRHeader(timestamp, testName, options) {
  return `# ============================================================================
# ${testName} - Generated by StickForStats
# ============================================================================
# Generated: ${timestamp}
# Significance Level (α): ${options.alpha || 0.05}
# Alternative Hypothesis: ${options.alternative || 'two-sided'}
#
# Scientific Foundation:
# - StickForStats uses gold-standard statistical methods
# - All calculations verified against established statistical software
# - Guardian System ensures assumption validation before analysis
#
# References:
# - Cohen, J. (1988). Statistical power analysis for the behavioral sciences.
# - Field, A. (2018). Discovering statistics using IBM SPSS statistics.
# ============================================================================

# Install required packages (run once)
# install.packages(c("car", "effectsize", "nortest", "lawstat"))

# Load libraries
library(stats)      # Base statistical functions
library(car)        # Levene's test, Type III ANOVA
library(effectsize) # Cohen's d, eta-squared, etc.

`;
}

function generateRDataSection(data, testType) {
  let code = `# ============================================================================
# DATA INPUT
# ============================================================================
# Note: Replace this data with your actual data or load from file
# Example: data <- read.csv("your_data.csv")
# ============================================================================

`;

  if (data.group1 && data.group2) {
    // Two-group comparison
    code += `# Group 1 data
group1 <- c(${formatDataForR(data.group1)})

# Group 2 data
group2 <- c(${formatDataForR(data.group2)})

# Create data frame for analysis
data <- data.frame(
  value = c(group1, group2),
  group = factor(c(rep("Group1", length(group1)), rep("Group2", length(group2))))
)

# Display sample sizes
cat("Group 1 n:", length(group1), "\\n")
cat("Group 2 n:", length(group2), "\\n")
cat("Total n:", length(group1) + length(group2), "\\n\\n")

`;
  } else if (data.groups && Array.isArray(data.groups)) {
    // Multiple groups (ANOVA)
    code += `# Multiple groups data
`;
    data.groups.forEach((group, i) => {
      code += `group${i + 1} <- c(${formatDataForR(group)})
`;
    });
    code += `
# Create data frame for analysis
values <- c(${data.groups.map((_, i) => `group${i + 1}`).join(', ')})
groups <- factor(c(${data.groups.map((g, i) => `rep("Group${i + 1}", length(group${i + 1}))`).join(', ')}))
data <- data.frame(value = values, group = groups)

# Display sample sizes
${data.groups.map((_, i) => `cat("Group ${i + 1} n:", length(group${i + 1}), "\\n")`).join('\n')}
cat("Total n:", nrow(data), "\\n\\n")

`;
  } else if (data.x && data.y) {
    // Correlation/regression
    code += `# Variable X
x <- c(${formatDataForR(data.x)})

# Variable Y
y <- c(${formatDataForR(data.y)})

# Create data frame
data <- data.frame(x = x, y = y)

cat("Sample size n:", length(x), "\\n\\n")

`;
  } else if (data.observed) {
    // Categorical data
    code += `# Observed frequencies
observed <- matrix(c(${formatDataForR(data.observed.flat())}),
                   nrow = ${data.observed.length},
                   byrow = TRUE)
rownames(observed) <- c(${data.rowNames ? data.rowNames.map(n => `"${n}"`).join(', ') : data.observed.map((_, i) => `"Row${i + 1}"`).join(', ')})
colnames(observed) <- c(${data.colNames ? data.colNames.map(n => `"${n}"`).join(', ') : data.observed[0].map((_, i) => `"Col${i + 1}"`).join(', ')})

cat("Contingency Table:\\n")
print(observed)
cat("\\n")

`;
  } else if (data.values) {
    // Single sample
    code += `# Sample data
values <- c(${formatDataForR(data.values)})

cat("Sample size n:", length(values), "\\n")
cat("Mean:", round(mean(values), 4), "\\n")
cat("SD:", round(sd(values), 4), "\\n\\n")

`;
  } else if (data.before && data.after) {
    // Paired data
    code += `# Before measurements
before <- c(${formatDataForR(data.before)})

# After measurements
after <- c(${formatDataForR(data.after)})

# Calculate differences
differences <- after - before

cat("Number of pairs:", length(before), "\\n")
cat("Mean difference:", round(mean(differences), 4), "\\n\\n")

`;
  }

  return code;
}

function generateRAssumptionChecks(testType, assumptions) {
  let code = `# ============================================================================
# ASSUMPTION CHECKS (Guardian System)
# ============================================================================
# StickForStats Guardian validates assumptions BEFORE analysis
# These checks ensure the statistical test is appropriate for your data
# ============================================================================

`;

  const checks = getRequiredAssumptions(testType);

  if (checks.includes('normality')) {
    code += `# 1. NORMALITY CHECK
# ============================================================================
# Shapiro-Wilk test (most powerful for n < 50)
# H0: Data is normally distributed
# If p < 0.05, normality assumption is violated
# ============================================================================

`;
    if (testType.includes('two-sample') || testType.includes('independent')) {
      code += `shapiro_g1 <- shapiro.test(group1)
shapiro_g2 <- shapiro.test(group2)
cat("Shapiro-Wilk Test (Group 1): W =", round(shapiro_g1$statistic, 4),
    ", p =", format(shapiro_g1$p.value, digits = 4), "\\n")
cat("Shapiro-Wilk Test (Group 2): W =", round(shapiro_g2$statistic, 4),
    ", p =", format(shapiro_g2$p.value, digits = 4), "\\n")

normality_ok <- shapiro_g1$p.value > 0.05 && shapiro_g2$p.value > 0.05
if (!normality_ok) {
  cat("\\n⚠️  WARNING: Normality assumption violated!\\n")
  cat("Consider using: Mann-Whitney U test (non-parametric alternative)\\n\\n")
} else {
  cat("✓ Normality assumption satisfied\\n\\n")
}

`;
    } else if (testType.includes('paired')) {
      code += `shapiro_diff <- shapiro.test(differences)
cat("Shapiro-Wilk Test (differences): W =", round(shapiro_diff$statistic, 4),
    ", p =", format(shapiro_diff$p.value, digits = 4), "\\n")

normality_ok <- shapiro_diff$p.value > 0.05
if (!normality_ok) {
  cat("\\n⚠️  WARNING: Normality assumption violated!\\n")
  cat("Consider using: Wilcoxon Signed-Rank test (non-parametric alternative)\\n\\n")
} else {
  cat("✓ Normality assumption satisfied\\n\\n")
}

`;
    } else if (testType.includes('anova')) {
      code += `# Check normality within each group
shapiro_results <- by(data$value, data$group, shapiro.test)
cat("Shapiro-Wilk Tests by Group:\\n")
for (grp in names(shapiro_results)) {
  cat("  ", grp, ": W =", round(shapiro_results[[grp]]$statistic, 4),
      ", p =", format(shapiro_results[[grp]]$p.value, digits = 4), "\\n")
}

# Alternative: Check normality of residuals after fitting model
model <- aov(value ~ group, data = data)
shapiro_resid <- shapiro.test(residuals(model))
cat("\\nShapiro-Wilk Test (residuals): W =", round(shapiro_resid$statistic, 4),
    ", p =", format(shapiro_resid$p.value, digits = 4), "\\n")

if (shapiro_resid$p.value < 0.05) {
  cat("\\n⚠️  WARNING: Normality assumption violated!\\n")
  cat("Consider using: Kruskal-Wallis test (non-parametric alternative)\\n\\n")
} else {
  cat("✓ Normality assumption satisfied\\n\\n")
}

`;
    } else {
      code += `shapiro_result <- shapiro.test(values)
cat("Shapiro-Wilk Test: W =", round(shapiro_result$statistic, 4),
    ", p =", format(shapiro_result$p.value, digits = 4), "\\n")

normality_ok <- shapiro_result$p.value > 0.05
if (!normality_ok) {
  cat("\\n⚠️  WARNING: Normality assumption violated!\\n")
  cat("Consider using non-parametric alternatives or data transformation\\n\\n")
} else {
  cat("✓ Normality assumption satisfied\\n\\n")
}

`;
    }
  }

  if (checks.includes('homogeneity')) {
    code += `# 2. HOMOGENEITY OF VARIANCE CHECK
# ============================================================================
# Levene's Test (robust to non-normality)
# H0: Variances are equal across groups
# If p < 0.05, homogeneity assumption is violated
# ============================================================================

levene_result <- leveneTest(value ~ group, data = data)
cat("Levene's Test: F =", round(levene_result$\`F value\`[1], 4),
    ", p =", format(levene_result$\`Pr(>F)\`[1], digits = 4), "\\n")

homogeneity_ok <- levene_result$\`Pr(>F)\`[1] > 0.05
if (!homogeneity_ok) {
  cat("\\n⚠️  WARNING: Homogeneity of variance violated!\\n")
  cat("Consider using: Welch's t-test or Welch's ANOVA\\n\\n")
} else {
  cat("✓ Homogeneity of variance satisfied\\n\\n")
}

`;
  }

  if (checks.includes('linearity')) {
    code += `# 2. LINEARITY CHECK
# ============================================================================
# Visual inspection and correlation test
# ============================================================================

# Correlation coefficient
r <- cor(x, y, method = "pearson")
cat("Pearson correlation r:", round(r, 4), "\\n")

# Visual check (create scatterplot with LOESS smoother)
plot(x, y, main = "Scatterplot with LOESS Fit",
     xlab = "X", ylab = "Y", pch = 19)
abline(lm(y ~ x), col = "blue", lwd = 2)
lines(lowess(x, y), col = "red", lwd = 2)
legend("topright", legend = c("Linear fit", "LOESS smoother"),
       col = c("blue", "red"), lwd = 2)

cat("If red (LOESS) and blue (linear) lines differ substantially,")
cat(" the linearity assumption may be violated.\\n\\n")

`;
  }

  // Add Guardian summary
  if (assumptions.violations && assumptions.violations.length > 0) {
    code += `# ============================================================================
# GUARDIAN SYSTEM SUMMARY
# ============================================================================
# StickForStats Guardian detected the following violations:
`;
    assumptions.violations.forEach(v => {
      code += `# - ${v.assumption}: ${v.message}
`;
    });
    code += `# ============================================================================

`;
  }

  return code;
}

function generateRTestCode(testType, data, options, results) {
  const alpha = options.alpha || 0.05;
  const alternative = options.alternative || 'two.sided';
  const altR = alternative === 'two-sided' ? 'two.sided' : alternative;

  let code = `# ============================================================================
# STATISTICAL TEST
# ============================================================================

`;

  switch (testType) {
    case 'independent-t':
    case 'two-sample-t':
      code += `# Independent Samples t-test
# H0: μ1 = μ2 (population means are equal)
# H1: μ1 ≠ μ2 (population means are different)

# Standard t-test (assumes equal variances)
t_result <- t.test(group1, group2,
                   alternative = "${altR}",
                   var.equal = TRUE,
                   conf.level = ${1 - alpha})

# Welch's t-test (does not assume equal variances) - RECOMMENDED
welch_result <- t.test(group1, group2,
                       alternative = "${altR}",
                       var.equal = FALSE,
                       conf.level = ${1 - alpha})

cat("\\n=== Student's t-test (equal variance assumed) ===\\n")
print(t_result)

cat("\\n=== Welch's t-test (unequal variance - RECOMMENDED) ===\\n")
print(welch_result)

# Store results
test_result <- welch_result  # Use Welch's by default

`;
      break;

    case 'paired-t':
      code += `# Paired Samples t-test
# H0: μd = 0 (mean difference is zero)
# H1: μd ≠ 0 (mean difference is not zero)

t_result <- t.test(before, after,
                   paired = TRUE,
                   alternative = "${altR}",
                   conf.level = ${1 - alpha})

cat("\\n=== Paired Samples t-test ===\\n")
print(t_result)

test_result <- t_result

`;
      break;

    case 'one-sample-t':
      code += `# One-Sample t-test
# H0: μ = ${options.mu || 0} (population mean equals hypothesized value)
# H1: μ ≠ ${options.mu || 0} (population mean differs from hypothesized value)

t_result <- t.test(values,
                   mu = ${options.mu || 0},
                   alternative = "${altR}",
                   conf.level = ${1 - alpha})

cat("\\n=== One-Sample t-test ===\\n")
print(t_result)

test_result <- t_result

`;
      break;

    case 'one-way-anova':
    case 'anova':
      code += `# One-Way ANOVA
# H0: All group means are equal (μ1 = μ2 = ... = μk)
# H1: At least one group mean differs

# Fit ANOVA model
model <- aov(value ~ group, data = data)

cat("\\n=== One-Way ANOVA ===\\n")
print(summary(model))

# If significant, perform post-hoc tests
if (summary(model)[[1]]$\`Pr(>F)\`[1] < ${alpha}) {
  cat("\\n=== Post-hoc Tests (Tukey HSD) ===\\n")
  print(TukeyHSD(model))
}

# Welch's ANOVA (robust to unequal variances)
cat("\\n=== Welch's ANOVA (robust alternative) ===\\n")
print(oneway.test(value ~ group, data = data, var.equal = FALSE))

test_result <- model

`;
      break;

    case 'pearson-correlation':
    case 'correlation':
      code += `# Pearson Correlation
# H0: ρ = 0 (no linear correlation)
# H1: ρ ≠ 0 (linear correlation exists)

cor_result <- cor.test(x, y,
                       method = "pearson",
                       alternative = "${altR}",
                       conf.level = ${1 - alpha})

cat("\\n=== Pearson Correlation ===\\n")
print(cor_result)

test_result <- cor_result

`;
      break;

    case 'spearman-correlation':
      code += `# Spearman Rank Correlation
# H0: ρs = 0 (no monotonic correlation)
# H1: ρs ≠ 0 (monotonic correlation exists)

cor_result <- cor.test(x, y,
                       method = "spearman",
                       alternative = "${altR}",
                       conf.level = ${1 - alpha})

cat("\\n=== Spearman Rank Correlation ===\\n")
print(cor_result)

test_result <- cor_result

`;
      break;

    case 'mann-whitney':
    case 'mann-whitney-u':
      code += `# Mann-Whitney U Test (Wilcoxon Rank-Sum)
# H0: The distributions of both groups are equal
# H1: The distributions differ

mw_result <- wilcox.test(group1, group2,
                         alternative = "${altR}",
                         conf.int = TRUE,
                         conf.level = ${1 - alpha})

cat("\\n=== Mann-Whitney U Test ===\\n")
print(mw_result)

test_result <- mw_result

`;
      break;

    case 'wilcoxon':
    case 'wilcoxon-signed-rank':
      code += `# Wilcoxon Signed-Rank Test
# H0: The median difference is zero
# H1: The median difference is not zero

wilcox_result <- wilcox.test(before, after,
                             paired = TRUE,
                             alternative = "${altR}",
                             conf.int = TRUE,
                             conf.level = ${1 - alpha})

cat("\\n=== Wilcoxon Signed-Rank Test ===\\n")
print(wilcox_result)

test_result <- wilcox_result

`;
      break;

    case 'kruskal-wallis':
      code += `# Kruskal-Wallis Test
# H0: All group distributions are equal
# H1: At least one group distribution differs

kw_result <- kruskal.test(value ~ group, data = data)

cat("\\n=== Kruskal-Wallis Test ===\\n")
print(kw_result)

# If significant, perform pairwise comparisons
if (kw_result$p.value < ${alpha}) {
  cat("\\n=== Pairwise Wilcoxon Tests (with Bonferroni correction) ===\\n")
  print(pairwise.wilcox.test(data$value, data$group, p.adjust.method = "bonferroni"))
}

test_result <- kw_result

`;
      break;

    case 'chi-square':
    case 'chi-square-independence':
      code += `# Chi-Square Test of Independence
# H0: Variables are independent
# H1: Variables are associated

chi_result <- chisq.test(observed)

cat("\\n=== Chi-Square Test of Independence ===\\n")
print(chi_result)

# Expected frequencies
cat("\\nExpected frequencies:\\n")
print(chi_result$expected)

# Check for expected frequency warning
if (any(chi_result$expected < 5)) {
  cat("\\n⚠️  WARNING: Some expected frequencies < 5\\n")
  cat("Consider using Fisher's Exact Test for small samples\\n")
}

test_result <- chi_result

`;
      break;

    case 'fisher-exact':
      code += `# Fisher's Exact Test
# H0: Variables are independent
# H1: Variables are associated
# Note: Preferred for small sample sizes or when expected frequencies < 5

fisher_result <- fisher.test(observed)

cat("\\n=== Fisher's Exact Test ===\\n")
print(fisher_result)

test_result <- fisher_result

`;
      break;

    case 'linear-regression':
    case 'regression':
      code += `# Simple Linear Regression
# Model: Y = β0 + β1*X + ε

model <- lm(y ~ x, data = data)

cat("\\n=== Linear Regression Model ===\\n")
print(summary(model))

# Confidence intervals for coefficients
cat("\\n=== 95% Confidence Intervals ===\\n")
print(confint(model))

# Diagnostic plots
par(mfrow = c(2, 2))
plot(model)
par(mfrow = c(1, 1))

test_result <- model

`;
      break;

    default:
      code += `# Test type "${testType}" - please implement specific test code
# This is a placeholder for the statistical test

`;
  }

  return code;
}

function generateREffectSize(testType, results) {
  let code = `# ============================================================================
# EFFECT SIZE CALCULATION
# ============================================================================
# Effect sizes are essential for practical significance
# Statistical significance ≠ practical importance
# ============================================================================

`;

  switch (testType) {
    case 'independent-t':
    case 'two-sample-t':
      code += `# Cohen's d for independent samples t-test
cohens_d <- effectsize::cohens_d(group1, group2)
cat("\\n=== Effect Size ===\\n")
print(cohens_d)

# Interpretation
d_value <- abs(cohens_d$Cohens_d)
interpretation <- ifelse(d_value < 0.2, "negligible",
                  ifelse(d_value < 0.5, "small",
                  ifelse(d_value < 0.8, "medium", "large")))
cat("Interpretation:", interpretation, "effect\\n")

`;
      break;

    case 'paired-t':
      code += `# Cohen's d for paired samples
cohens_d <- effectsize::cohens_d(differences)
cat("\\n=== Effect Size ===\\n")
print(cohens_d)

# Interpretation
d_value <- abs(cohens_d$Cohens_d)
interpretation <- ifelse(d_value < 0.2, "negligible",
                  ifelse(d_value < 0.5, "small",
                  ifelse(d_value < 0.8, "medium", "large")))
cat("Interpretation:", interpretation, "effect\\n")

`;
      break;

    case 'one-way-anova':
    case 'anova':
      code += `# Eta-squared and Omega-squared for ANOVA
eta_sq <- effectsize::eta_squared(model)
omega_sq <- effectsize::omega_squared(model)

cat("\\n=== Effect Sizes ===\\n")
cat("Eta-squared (η²):", round(eta_sq$Eta2, 4), "\\n")
cat("Omega-squared (ω²):", round(omega_sq$Omega2, 4), "(less biased)\\n")

# Interpretation (Cohen's benchmarks for f)
eta <- eta_sq$Eta2
interpretation <- ifelse(eta < 0.01, "negligible",
                  ifelse(eta < 0.06, "small",
                  ifelse(eta < 0.14, "medium", "large")))
cat("Interpretation:", interpretation, "effect\\n")

`;
      break;

    case 'pearson-correlation':
    case 'spearman-correlation':
    case 'correlation':
      code += `# Correlation coefficient IS the effect size
r_value <- abs(cor_result$estimate)
cat("\\n=== Effect Size ===\\n")
cat("Correlation r:", round(cor_result$estimate, 4), "\\n")
cat("Coefficient of determination r²:", round(r_value^2, 4), "\\n")

# Interpretation (Cohen's benchmarks)
interpretation <- ifelse(r_value < 0.1, "negligible",
                  ifelse(r_value < 0.3, "small",
                  ifelse(r_value < 0.5, "medium", "large")))
cat("Interpretation:", interpretation, "effect\\n")

`;
      break;

    case 'chi-square':
    case 'chi-square-independence':
      code += `# Cramér's V for chi-square test
cramers_v <- effectsize::cramers_v(observed)
cat("\\n=== Effect Size ===\\n")
print(cramers_v)

# Interpretation depends on df
v_value <- cramers_v$Cramers_v
interpretation <- ifelse(v_value < 0.1, "negligible",
                  ifelse(v_value < 0.3, "small",
                  ifelse(v_value < 0.5, "medium", "large")))
cat("Interpretation:", interpretation, "effect\\n")

`;
      break;

    case 'mann-whitney':
    case 'mann-whitney-u':
      code += `# Rank-biserial correlation for Mann-Whitney
# r = 1 - (2U)/(n1*n2)
n1 <- length(group1)
n2 <- length(group2)
U <- mw_result$statistic
r_rb <- 1 - (2 * U) / (n1 * n2)

cat("\\n=== Effect Size ===\\n")
cat("Rank-biserial correlation r:", round(r_rb, 4), "\\n")

# Interpretation (same as r)
r_value <- abs(r_rb)
interpretation <- ifelse(r_value < 0.1, "negligible",
                  ifelse(r_value < 0.3, "small",
                  ifelse(r_value < 0.5, "medium", "large")))
cat("Interpretation:", interpretation, "effect\\n")

`;
      break;

    case 'linear-regression':
    case 'regression':
      code += `# R-squared for regression
r_squared <- summary(model)$r.squared
adj_r_squared <- summary(model)$adj.r.squared

cat("\\n=== Effect Size ===\\n")
cat("R-squared:", round(r_squared, 4), "\\n")
cat("Adjusted R-squared:", round(adj_r_squared, 4), "\\n")

# Cohen's f² for regression
f_squared <- r_squared / (1 - r_squared)
cat("Cohen's f²:", round(f_squared, 4), "\\n")

# Interpretation
interpretation <- ifelse(f_squared < 0.02, "negligible",
                  ifelse(f_squared < 0.15, "small",
                  ifelse(f_squared < 0.35, "medium", "large")))
cat("Interpretation:", interpretation, "effect\\n")

`;
      break;

    default:
      code += `# Effect size calculation for this test type
# Please calculate the appropriate effect size metric

`;
  }

  return code;
}

function generateRInterpretation(testType, results) {
  return `# ============================================================================
# RESULTS INTERPRETATION
# ============================================================================

alpha <- ${results.alpha || 0.05}
p_value <- ${results.pValue ? results.pValue.toFixed(6) : 'test_result$p.value'}

cat("\\n=== INTERPRETATION ===\\n")
cat("Significance level (α):", alpha, "\\n")
cat("p-value:", format(p_value, digits = 4), "\\n\\n")

if (p_value < alpha) {
  cat("RESULT: STATISTICALLY SIGNIFICANT\\n")
  cat("The null hypothesis is rejected at α =", alpha, "\\n")
  cat("There is sufficient evidence to conclude that the effect exists.\\n")
} else {
  cat("RESULT: NOT STATISTICALLY SIGNIFICANT\\n")
  cat("The null hypothesis cannot be rejected at α =", alpha, "\\n")
  cat("There is insufficient evidence to conclude that the effect exists.\\n")
}

cat("\\nIMPORTANT: Consider effect size for practical significance!\\n")
cat("Statistical significance ≠ practical importance\\n")

`;
}

function generateRFooter(testType) {
  return `# ============================================================================
# REPRODUCIBILITY INFORMATION
# ============================================================================
cat("\\n=== Session Info ===\\n")
print(sessionInfo())

# ============================================================================
# Generated by StickForStats (https://stickforstats.com)
# Guardian-validated statistical analysis with scientific integrity
# ============================================================================
`;
}

// ============================================================================
// PYTHON CODE GENERATION SECTIONS
// ============================================================================

function generatePythonHeader(timestamp, testName, options) {
  return `"""
============================================================================
${testName} - Generated by StickForStats
============================================================================
Generated: ${timestamp}
Significance Level (α): ${options.alpha || 0.05}
Alternative Hypothesis: ${options.alternative || 'two-sided'}

Scientific Foundation:
- StickForStats uses gold-standard statistical methods
- All calculations verified against established statistical software
- Guardian System ensures assumption validation before analysis

References:
- Cohen, J. (1988). Statistical power analysis for the behavioral sciences.
- Field, A. (2018). Discovering statistics using IBM SPSS statistics.
============================================================================
"""

# Install required packages (run once in terminal):
# pip install numpy pandas scipy statsmodels pingouin

import numpy as np
import pandas as pd
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Optional: for effect sizes and advanced tests
try:
    import pingouin as pg
    PINGOUIN_AVAILABLE = True
except ImportError:
    PINGOUIN_AVAILABLE = False
    print("Note: Install pingouin for additional effect size calculations")
    print("pip install pingouin")

`;
}

function generatePythonDataSection(data, testType) {
  let code = `# ============================================================================
# DATA INPUT
# ============================================================================
# Note: Replace this data with your actual data or load from file
# Example: df = pd.read_csv("your_data.csv")
# ============================================================================

`;

  if (data.group1 && data.group2) {
    code += `# Group 1 data
group1 = np.array([${formatDataForPython(data.group1)}])

# Group 2 data
group2 = np.array([${formatDataForPython(data.group2)}])

# Create DataFrame for analysis
data = pd.DataFrame({
    'value': np.concatenate([group1, group2]),
    'group': ['Group1'] * len(group1) + ['Group2'] * len(group2)
})

print(f"Group 1 n: {len(group1)}")
print(f"Group 2 n: {len(group2)}")
print(f"Total n: {len(group1) + len(group2)}\\n")

`;
  } else if (data.groups && Array.isArray(data.groups)) {
    code += `# Multiple groups data
`;
    data.groups.forEach((group, i) => {
      code += `group${i + 1} = np.array([${formatDataForPython(group)}])
`;
    });
    code += `
# Create DataFrame for analysis
all_values = np.concatenate([${data.groups.map((_, i) => `group${i + 1}`).join(', ')}])
all_groups = ${data.groups.map((g, i) => `['Group${i + 1}'] * len(group${i + 1})`).join(' + ')}
data = pd.DataFrame({'value': all_values, 'group': all_groups})

# Display sample sizes
${data.groups.map((_, i) => `print(f"Group ${i + 1} n: {len(group${i + 1})}")`).join('\n')}
print(f"Total n: {len(data)}\\n")

`;
  } else if (data.x && data.y) {
    code += `# Variable X
x = np.array([${formatDataForPython(data.x)}])

# Variable Y
y = np.array([${formatDataForPython(data.y)}])

# Create DataFrame
data = pd.DataFrame({'x': x, 'y': y})

print(f"Sample size n: {len(x)}\\n")

`;
  } else if (data.observed) {
    code += `# Observed frequencies (contingency table)
observed = np.array([
${data.observed.map(row => `    [${row.join(', ')}]`).join(',\n')}
])

row_names = [${data.rowNames ? data.rowNames.map(n => `'${n}'`).join(', ') : data.observed.map((_, i) => `'Row${i + 1}'`).join(', ')}]
col_names = [${data.colNames ? data.colNames.map(n => `'${n}'`).join(', ') : data.observed[0].map((_, i) => `'Col${i + 1}'`).join(', ')}]

print("Contingency Table:")
print(pd.DataFrame(observed, index=row_names, columns=col_names))
print()

`;
  } else if (data.values) {
    code += `# Sample data
values = np.array([${formatDataForPython(data.values)}])

print(f"Sample size n: {len(values)}")
print(f"Mean: {np.mean(values):.4f}")
print(f"SD: {np.std(values, ddof=1):.4f}\\n")

`;
  } else if (data.before && data.after) {
    code += `# Before measurements
before = np.array([${formatDataForPython(data.before)}])

# After measurements
after = np.array([${formatDataForPython(data.after)}])

# Calculate differences
differences = after - before

print(f"Number of pairs: {len(before)}")
print(f"Mean difference: {np.mean(differences):.4f}\\n")

`;
  }

  return code;
}

function generatePythonAssumptionChecks(testType, assumptions) {
  let code = `# ============================================================================
# ASSUMPTION CHECKS (Guardian System)
# ============================================================================
# StickForStats Guardian validates assumptions BEFORE analysis
# These checks ensure the statistical test is appropriate for your data
# ============================================================================

`;

  const checks = getRequiredAssumptions(testType);

  if (checks.includes('normality')) {
    code += `# 1. NORMALITY CHECK
# ============================================================================
# Shapiro-Wilk test (most powerful for n < 50)
# H0: Data is normally distributed
# If p < 0.05, normality assumption is violated
# ============================================================================

`;
    if (testType.includes('two-sample') || testType.includes('independent')) {
      code += `shapiro_g1 = stats.shapiro(group1)
shapiro_g2 = stats.shapiro(group2)
print(f"Shapiro-Wilk Test (Group 1): W = {shapiro_g1.statistic:.4f}, p = {shapiro_g1.pvalue:.4f}")
print(f"Shapiro-Wilk Test (Group 2): W = {shapiro_g2.statistic:.4f}, p = {shapiro_g2.pvalue:.4f}")

normality_ok = shapiro_g1.pvalue > 0.05 and shapiro_g2.pvalue > 0.05
if not normality_ok:
    print("\\n⚠️  WARNING: Normality assumption violated!")
    print("Consider using: Mann-Whitney U test (non-parametric alternative)\\n")
else:
    print("✓ Normality assumption satisfied\\n")

`;
    } else if (testType.includes('paired')) {
      code += `shapiro_diff = stats.shapiro(differences)
print(f"Shapiro-Wilk Test (differences): W = {shapiro_diff.statistic:.4f}, p = {shapiro_diff.pvalue:.4f}")

normality_ok = shapiro_diff.pvalue > 0.05
if not normality_ok:
    print("\\n⚠️  WARNING: Normality assumption violated!")
    print("Consider using: Wilcoxon Signed-Rank test (non-parametric alternative)\\n")
else:
    print("✓ Normality assumption satisfied\\n")

`;
    } else if (testType.includes('anova')) {
      code += `# Check normality within each group
print("Shapiro-Wilk Tests by Group:")
for group_name in data['group'].unique():
    group_data = data[data['group'] == group_name]['value']
    stat, pval = stats.shapiro(group_data)
    print(f"  {group_name}: W = {stat:.4f}, p = {pval:.4f}")

# Check normality assumption overall
all_normal = all(
    stats.shapiro(data[data['group'] == g]['value']).pvalue > 0.05
    for g in data['group'].unique()
)
if not all_normal:
    print("\\n⚠️  WARNING: Normality assumption violated!")
    print("Consider using: Kruskal-Wallis test (non-parametric alternative)\\n")
else:
    print("✓ Normality assumption satisfied\\n")

`;
    } else {
      code += `shapiro_result = stats.shapiro(values)
print(f"Shapiro-Wilk Test: W = {shapiro_result.statistic:.4f}, p = {shapiro_result.pvalue:.4f}")

normality_ok = shapiro_result.pvalue > 0.05
if not normality_ok:
    print("\\n⚠️  WARNING: Normality assumption violated!")
    print("Consider using non-parametric alternatives or data transformation\\n")
else:
    print("✓ Normality assumption satisfied\\n")

`;
    }
  }

  if (checks.includes('homogeneity')) {
    code += `# 2. HOMOGENEITY OF VARIANCE CHECK
# ============================================================================
# Levene's Test (robust to non-normality)
# H0: Variances are equal across groups
# If p < 0.05, homogeneity assumption is violated
# ============================================================================

groups_list = [data[data['group'] == g]['value'].values for g in data['group'].unique()]
levene_result = stats.levene(*groups_list)
print(f"Levene's Test: F = {levene_result.statistic:.4f}, p = {levene_result.pvalue:.4f}")

homogeneity_ok = levene_result.pvalue > 0.05
if not homogeneity_ok:
    print("\\n⚠️  WARNING: Homogeneity of variance violated!")
    print("Consider using: Welch's t-test or Welch's ANOVA\\n")
else:
    print("✓ Homogeneity of variance satisfied\\n")

`;
  }

  if (checks.includes('linearity')) {
    code += `# 2. LINEARITY CHECK
# ============================================================================
# Visual inspection and correlation test
# ============================================================================

import matplotlib.pyplot as plt
from scipy.stats import pearsonr

# Correlation coefficient
r, p = pearsonr(x, y)
print(f"Pearson correlation r: {r:.4f}")

# Visual check
fig, ax = plt.subplots(figsize=(8, 6))
ax.scatter(x, y, alpha=0.7, label='Data points')

# Linear fit
z = np.polyfit(x, y, 1)
p_fit = np.poly1d(z)
ax.plot(x, p_fit(x), 'b-', linewidth=2, label='Linear fit')

# LOWESS smoother (if statsmodels available)
try:
    from statsmodels.nonparametric.smoothers_lowess import lowess
    smoothed = lowess(y, x, frac=0.5)
    ax.plot(smoothed[:, 0], smoothed[:, 1], 'r-', linewidth=2, label='LOWESS smoother')
except ImportError:
    pass

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_title('Scatterplot with Linear Fit')
ax.legend()
plt.tight_layout()
plt.show()

print("If red (LOWESS) and blue (linear) lines differ substantially,")
print("the linearity assumption may be violated.\\n")

`;
  }

  return code;
}

function generatePythonTestCode(testType, data, options, results) {
  const alpha = options.alpha || 0.05;
  const _alternative = options.alternative || 'two-sided';

  let code = `# ============================================================================
# STATISTICAL TEST
# ============================================================================

`;

  switch (testType) {
    case 'independent-t':
    case 'two-sample-t':
      code += `# Independent Samples t-test
# H0: μ1 = μ2 (population means are equal)
# H1: μ1 ≠ μ2 (population means are different)

# Standard t-test (assumes equal variances)
t_stat, p_value_equal = stats.ttest_ind(group1, group2, equal_var=True)
print("\\n=== Student's t-test (equal variance assumed) ===")
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value_equal:.6f}")

# Welch's t-test (does not assume equal variances) - RECOMMENDED
t_stat_welch, p_value_welch = stats.ttest_ind(group1, group2, equal_var=False)
print("\\n=== Welch's t-test (unequal variance - RECOMMENDED) ===")
print(f"t-statistic: {t_stat_welch:.4f}")
print(f"p-value: {p_value_welch:.6f}")

# Confidence interval for mean difference
mean_diff = np.mean(group1) - np.mean(group2)
se_diff = np.sqrt(np.var(group1, ddof=1)/len(group1) + np.var(group2, ddof=1)/len(group2))
df = len(group1) + len(group2) - 2
t_crit = stats.t.ppf(1 - ${alpha}/2, df)
ci_lower = mean_diff - t_crit * se_diff
ci_upper = mean_diff + t_crit * se_diff
print(f"\\n{int((1-${alpha})*100)}% CI for mean difference: [{ci_lower:.4f}, {ci_upper:.4f}]")

# Store results
test_statistic = t_stat_welch
p_value = p_value_welch

`;
      break;

    case 'paired-t':
      code += `# Paired Samples t-test
# H0: μd = 0 (mean difference is zero)
# H1: μd ≠ 0 (mean difference is not zero)

t_stat, p_value = stats.ttest_rel(after, before)

print("\\n=== Paired Samples t-test ===")
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.6f}")
print(f"Mean difference: {np.mean(differences):.4f}")
print(f"SD of differences: {np.std(differences, ddof=1):.4f}")

# Confidence interval
se_diff = np.std(differences, ddof=1) / np.sqrt(len(differences))
t_crit = stats.t.ppf(1 - ${alpha}/2, len(differences) - 1)
ci_lower = np.mean(differences) - t_crit * se_diff
ci_upper = np.mean(differences) + t_crit * se_diff
print(f"{int((1-${alpha})*100)}% CI: [{ci_lower:.4f}, {ci_upper:.4f}]")

test_statistic = t_stat

`;
      break;

    case 'one-sample-t':
      code += `# One-Sample t-test
# H0: μ = ${options.mu || 0} (population mean equals hypothesized value)
# H1: μ ≠ ${options.mu || 0} (population mean differs from hypothesized value)

mu = ${options.mu || 0}
t_stat, p_value = stats.ttest_1samp(values, mu)

print("\\n=== One-Sample t-test ===")
print(f"Hypothesized mean (μ₀): {mu}")
print(f"Sample mean: {np.mean(values):.4f}")
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.6f}")

# Confidence interval
se = np.std(values, ddof=1) / np.sqrt(len(values))
t_crit = stats.t.ppf(1 - ${alpha}/2, len(values) - 1)
ci_lower = np.mean(values) - t_crit * se
ci_upper = np.mean(values) + t_crit * se
print(f"{int((1-${alpha})*100)}% CI: [{ci_lower:.4f}, {ci_upper:.4f}]")

test_statistic = t_stat

`;
      break;

    case 'one-way-anova':
    case 'anova':
      code += `# One-Way ANOVA
# H0: All group means are equal (μ1 = μ2 = ... = μk)
# H1: At least one group mean differs

groups_list = [data[data['group'] == g]['value'].values for g in data['group'].unique()]
f_stat, p_value = stats.f_oneway(*groups_list)

print("\\n=== One-Way ANOVA ===")
print(f"F-statistic: {f_stat:.4f}")
print(f"p-value: {p_value:.6f}")

# Group statistics
print("\\nGroup Statistics:")
print(data.groupby('group')['value'].agg(['mean', 'std', 'count']))

# Post-hoc tests if significant
if p_value < ${alpha}:
    print("\\n=== Post-hoc Tests (Tukey HSD) ===")
    if PINGOUIN_AVAILABLE:
        posthoc = pg.pairwise_tukey(data=data, dv='value', between='group')
        print(posthoc)
    else:
        from statsmodels.stats.multicomp import pairwise_tukeyhsd
        tukey = pairwise_tukeyhsd(data['value'], data['group'], alpha=${alpha})
        print(tukey)

test_statistic = f_stat

`;
      break;

    case 'pearson-correlation':
    case 'correlation':
      code += `# Pearson Correlation
# H0: ρ = 0 (no linear correlation)
# H1: ρ ≠ 0 (linear correlation exists)

r, p_value = stats.pearsonr(x, y)

print("\\n=== Pearson Correlation ===")
print(f"Correlation coefficient r: {r:.4f}")
print(f"p-value: {p_value:.6f}")
print(f"Coefficient of determination r²: {r**2:.4f}")

# Confidence interval for r (Fisher's z transformation)
n = len(x)
z = 0.5 * np.log((1 + r) / (1 - r))  # Fisher's z
se_z = 1 / np.sqrt(n - 3)
z_crit = stats.norm.ppf(1 - ${alpha}/2)
z_lower = z - z_crit * se_z
z_upper = z + z_crit * se_z
r_lower = (np.exp(2 * z_lower) - 1) / (np.exp(2 * z_lower) + 1)
r_upper = (np.exp(2 * z_upper) - 1) / (np.exp(2 * z_upper) + 1)
print(f"{int((1-${alpha})*100)}% CI for r: [{r_lower:.4f}, {r_upper:.4f}]")

test_statistic = r

`;
      break;

    case 'spearman-correlation':
      code += `# Spearman Rank Correlation
# H0: ρs = 0 (no monotonic correlation)
# H1: ρs ≠ 0 (monotonic correlation exists)

rho, p_value = stats.spearmanr(x, y)

print("\\n=== Spearman Rank Correlation ===")
print(f"Spearman's ρ: {rho:.4f}")
print(f"p-value: {p_value:.6f}")

test_statistic = rho

`;
      break;

    case 'mann-whitney':
    case 'mann-whitney-u':
      code += `# Mann-Whitney U Test (Wilcoxon Rank-Sum)
# H0: The distributions of both groups are equal
# H1: The distributions differ

u_stat, p_value = stats.mannwhitneyu(group1, group2, alternative='two-sided')

print("\\n=== Mann-Whitney U Test ===")
print(f"U-statistic: {u_stat:.4f}")
print(f"p-value: {p_value:.6f}")

# Calculate rank-biserial correlation (effect size)
n1, n2 = len(group1), len(group2)
r_rb = 1 - (2 * u_stat) / (n1 * n2)
print(f"Rank-biserial correlation r: {r_rb:.4f}")

test_statistic = u_stat

`;
      break;

    case 'wilcoxon':
    case 'wilcoxon-signed-rank':
      code += `# Wilcoxon Signed-Rank Test
# H0: The median difference is zero
# H1: The median difference is not zero

w_stat, p_value = stats.wilcoxon(after, before, alternative='two-sided')

print("\\n=== Wilcoxon Signed-Rank Test ===")
print(f"W-statistic: {w_stat:.4f}")
print(f"p-value: {p_value:.6f}")
print(f"Median difference: {np.median(differences):.4f}")

test_statistic = w_stat

`;
      break;

    case 'kruskal-wallis':
      code += `# Kruskal-Wallis Test
# H0: All group distributions are equal
# H1: At least one group distribution differs

groups_list = [data[data['group'] == g]['value'].values for g in data['group'].unique()]
h_stat, p_value = stats.kruskal(*groups_list)

print("\\n=== Kruskal-Wallis Test ===")
print(f"H-statistic: {h_stat:.4f}")
print(f"p-value: {p_value:.6f}")

# Post-hoc pairwise comparisons if significant
if p_value < ${alpha}:
    print("\\n=== Post-hoc Pairwise Tests (Dunn's test with Bonferroni) ===")
    if PINGOUIN_AVAILABLE:
        posthoc = pg.pairwise_tests(data=data, dv='value', between='group',
                                     parametric=False, padjust='bonf')
        print(posthoc)
    else:
        print("Install pingouin for post-hoc tests: pip install pingouin")

test_statistic = h_stat

`;
      break;

    case 'chi-square':
    case 'chi-square-independence':
      code += `# Chi-Square Test of Independence
# H0: Variables are independent
# H1: Variables are associated

chi2, p_value, dof, expected = stats.chi2_contingency(observed)

print("\\n=== Chi-Square Test of Independence ===")
print(f"Chi-square statistic: {chi2:.4f}")
print(f"p-value: {p_value:.6f}")
print(f"Degrees of freedom: {dof}")

print("\\nExpected frequencies:")
print(pd.DataFrame(expected, index=row_names, columns=col_names).round(2))

# Check expected frequency assumption
if np.any(expected < 5):
    print("\\n⚠️  WARNING: Some expected frequencies < 5")
    print("Consider using Fisher's Exact Test for small samples")

test_statistic = chi2

`;
      break;

    case 'fisher-exact':
      code += `# Fisher's Exact Test
# H0: Variables are independent
# H1: Variables are associated
# Note: For 2x2 tables only in scipy

if observed.shape == (2, 2):
    odds_ratio, p_value = stats.fisher_exact(observed)
    print("\\n=== Fisher's Exact Test ===")
    print(f"Odds ratio: {odds_ratio:.4f}")
    print(f"p-value: {p_value:.6f}")
    test_statistic = odds_ratio
else:
    print("Fisher's exact test in scipy is limited to 2x2 tables")
    print("For larger tables, use R or install 'fisher' package")
    test_statistic = None
    p_value = None

`;
      break;

    case 'linear-regression':
    case 'regression':
      code += `# Simple Linear Regression
# Model: Y = β0 + β1*X + ε

from scipy.stats import linregress
import statsmodels.api as sm

# Simple approach with scipy
slope, intercept, r_value, p_value, std_err = linregress(x, y)

print("\\n=== Simple Linear Regression (scipy) ===")
print(f"Slope (β1): {slope:.4f}")
print(f"Intercept (β0): {intercept:.4f}")
print(f"R-squared: {r_value**2:.4f}")
print(f"p-value: {p_value:.6f}")
print(f"Standard error: {std_err:.4f}")

# More detailed analysis with statsmodels
X = sm.add_constant(x)  # Add intercept
model = sm.OLS(y, X).fit()

print("\\n=== Detailed Regression Analysis (statsmodels) ===")
print(model.summary())

test_statistic = slope

`;
      break;

    default:
      code += `# Test type "${testType}" - please implement specific test code
# This is a placeholder for the statistical test
print("Test implementation needed for: ${testType}")

`;
  }

  return code;
}

function generatePythonEffectSize(testType, results) {
  let code = `# ============================================================================
# EFFECT SIZE CALCULATION
# ============================================================================
# Effect sizes are essential for practical significance
# Statistical significance ≠ practical importance
# ============================================================================

`;

  switch (testType) {
    case 'independent-t':
    case 'two-sample-t':
      code += `# Cohen's d for independent samples t-test
def cohens_d(group1, group2):
    n1, n2 = len(group1), len(group2)
    var1, var2 = np.var(group1, ddof=1), np.var(group2, ddof=1)
    pooled_std = np.sqrt(((n1 - 1) * var1 + (n2 - 1) * var2) / (n1 + n2 - 2))
    return (np.mean(group1) - np.mean(group2)) / pooled_std

d = cohens_d(group1, group2)
print(f"\\n=== Effect Size ===")
print(f"Cohen's d: {d:.4f}")

# Interpretation
d_abs = abs(d)
if d_abs < 0.2:
    interpretation = "negligible"
elif d_abs < 0.5:
    interpretation = "small"
elif d_abs < 0.8:
    interpretation = "medium"
else:
    interpretation = "large"
print(f"Interpretation: {interpretation} effect")

`;
      break;

    case 'paired-t':
      code += `# Cohen's d for paired samples (using SD of differences)
d = np.mean(differences) / np.std(differences, ddof=1)
print(f"\\n=== Effect Size ===")
print(f"Cohen's d: {d:.4f}")

# Interpretation
d_abs = abs(d)
if d_abs < 0.2:
    interpretation = "negligible"
elif d_abs < 0.5:
    interpretation = "small"
elif d_abs < 0.8:
    interpretation = "medium"
else:
    interpretation = "large"
print(f"Interpretation: {interpretation} effect")

`;
      break;

    case 'one-way-anova':
    case 'anova':
      code += `# Eta-squared for ANOVA
# η² = SS_between / SS_total
groups_list = [data[data['group'] == g]['value'].values for g in data['group'].unique()]
grand_mean = data['value'].mean()

ss_between = sum(len(g) * (np.mean(g) - grand_mean)**2 for g in groups_list)
ss_total = sum((data['value'] - grand_mean)**2)
eta_squared = ss_between / ss_total

# Omega-squared (less biased)
k = len(groups_list)
n = len(data)
ms_within = (ss_total - ss_between) / (n - k)
omega_squared = (ss_between - (k - 1) * ms_within) / (ss_total + ms_within)

print(f"\\n=== Effect Sizes ===")
print(f"Eta-squared (η²): {eta_squared:.4f}")
print(f"Omega-squared (ω²): {omega_squared:.4f} (less biased)")

# Interpretation
if eta_squared < 0.01:
    interpretation = "negligible"
elif eta_squared < 0.06:
    interpretation = "small"
elif eta_squared < 0.14:
    interpretation = "medium"
else:
    interpretation = "large"
print(f"Interpretation: {interpretation} effect")

`;
      break;

    case 'pearson-correlation':
    case 'spearman-correlation':
    case 'correlation':
      code += `# Correlation coefficient IS the effect size
r_value = abs(test_statistic)
print(f"\\n=== Effect Size ===")
print(f"Correlation r: {test_statistic:.4f}")
print(f"Coefficient of determination r²: {r_value**2:.4f}")

# Interpretation (Cohen's benchmarks)
if r_value < 0.1:
    interpretation = "negligible"
elif r_value < 0.3:
    interpretation = "small"
elif r_value < 0.5:
    interpretation = "medium"
else:
    interpretation = "large"
print(f"Interpretation: {interpretation} effect")

`;
      break;

    case 'chi-square':
    case 'chi-square-independence':
      code += `# Cramér's V for chi-square test
n = np.sum(observed)
min_dim = min(observed.shape) - 1
cramers_v = np.sqrt(chi2 / (n * min_dim))

print(f"\\n=== Effect Size ===")
print(f"Cramér's V: {cramers_v:.4f}")

# Interpretation
if cramers_v < 0.1:
    interpretation = "negligible"
elif cramers_v < 0.3:
    interpretation = "small"
elif cramers_v < 0.5:
    interpretation = "medium"
else:
    interpretation = "large"
print(f"Interpretation: {interpretation} effect")

`;
      break;

    case 'mann-whitney':
    case 'mann-whitney-u':
      code += `# Rank-biserial correlation (already calculated above)
print(f"\\n=== Effect Size ===")
print(f"Rank-biserial correlation r: {r_rb:.4f}")

# Interpretation
r_abs = abs(r_rb)
if r_abs < 0.1:
    interpretation = "negligible"
elif r_abs < 0.3:
    interpretation = "small"
elif r_abs < 0.5:
    interpretation = "medium"
else:
    interpretation = "large"
print(f"Interpretation: {interpretation} effect")

`;
      break;

    case 'linear-regression':
    case 'regression':
      code += `# R-squared and Cohen's f² for regression
r_squared = r_value ** 2
f_squared = r_squared / (1 - r_squared) if r_squared < 1 else float('inf')

print(f"\\n=== Effect Size ===")
print(f"R-squared: {r_squared:.4f}")
print(f"Cohen's f²: {f_squared:.4f}")

# Interpretation
if f_squared < 0.02:
    interpretation = "negligible"
elif f_squared < 0.15:
    interpretation = "small"
elif f_squared < 0.35:
    interpretation = "medium"
else:
    interpretation = "large"
print(f"Interpretation: {interpretation} effect")

`;
      break;

    default:
      code += `# Effect size calculation for this test type
print("\\n=== Effect Size ===")
print("Please calculate appropriate effect size metric for this test")

`;
  }

  return code;
}

function generatePythonInterpretation(testType, results) {
  return `# ============================================================================
# RESULTS INTERPRETATION
# ============================================================================

alpha = ${results.alpha || 0.05}

print(f"\\n=== INTERPRETATION ===")
print(f"Significance level (α): {alpha}")
print(f"p-value: {p_value:.6f}")

if p_value < alpha:
    print("\\nRESULT: STATISTICALLY SIGNIFICANT")
    print(f"The null hypothesis is rejected at α = {alpha}")
    print("There is sufficient evidence to conclude that the effect exists.")
else:
    print("\\nRESULT: NOT STATISTICALLY SIGNIFICANT")
    print(f"The null hypothesis cannot be rejected at α = {alpha}")
    print("There is insufficient evidence to conclude that the effect exists.")

print("\\nIMPORTANT: Consider effect size for practical significance!")
print("Statistical significance ≠ practical importance")

`;
}

function generatePythonFooter(testType) {
  return `# ============================================================================
# REPRODUCIBILITY INFORMATION
# ============================================================================
import sys
print(f"\\n=== Environment Info ===")
print(f"Python version: {sys.version}")
print(f"NumPy version: {np.__version__}")
print(f"SciPy version: {stats.scipy.version.version if hasattr(stats, 'scipy') else 'N/A'}")
print(f"Pandas version: {pd.__version__}")

# ============================================================================
# Generated by StickForStats (https://stickforstats.com)
# Guardian-validated statistical analysis with scientific integrity
# ============================================================================
`;
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

function getTestName(testType) {
  const names = {
    'independent-t': 'Independent Samples t-test',
    'two-sample-t': 'Independent Samples t-test',
    'paired-t': 'Paired Samples t-test',
    'one-sample-t': 'One-Sample t-test',
    'one-way-anova': 'One-Way ANOVA',
    'anova': 'One-Way ANOVA',
    'two-way-anova': 'Two-Way ANOVA',
    'pearson-correlation': 'Pearson Correlation',
    'spearman-correlation': 'Spearman Rank Correlation',
    'correlation': 'Pearson Correlation',
    'mann-whitney': 'Mann-Whitney U Test',
    'mann-whitney-u': 'Mann-Whitney U Test',
    'wilcoxon': 'Wilcoxon Signed-Rank Test',
    'wilcoxon-signed-rank': 'Wilcoxon Signed-Rank Test',
    'kruskal-wallis': 'Kruskal-Wallis Test',
    'chi-square': 'Chi-Square Test of Independence',
    'chi-square-independence': 'Chi-Square Test of Independence',
    'chi-square-goodness': 'Chi-Square Goodness of Fit',
    'fisher-exact': "Fisher's Exact Test",
    'mcnemar': "McNemar's Test",
    'linear-regression': 'Simple Linear Regression',
    'regression': 'Linear Regression',
    'multiple-regression': 'Multiple Linear Regression'
  };
  return names[testType] || testType;
}

function getRequiredAssumptions(testType) {
  const assumptions = {
    'independent-t': ['normality', 'homogeneity'],
    'two-sample-t': ['normality', 'homogeneity'],
    'paired-t': ['normality'],
    'one-sample-t': ['normality'],
    'one-way-anova': ['normality', 'homogeneity'],
    'anova': ['normality', 'homogeneity'],
    'pearson-correlation': ['normality', 'linearity'],
    'correlation': ['normality', 'linearity'],
    'linear-regression': ['normality', 'linearity', 'homoscedasticity'],
    'regression': ['normality', 'linearity', 'homoscedasticity'],
    // Non-parametric tests have fewer assumptions
    'mann-whitney': [],
    'wilcoxon': [],
    'kruskal-wallis': [],
    'chi-square': [],
    'fisher-exact': [],
    'spearman-correlation': []
  };
  return assumptions[testType] || [];
}

function formatDataForR(data) {
  if (!Array.isArray(data)) return String(data);
  return data.map(v => {
    if (typeof v === 'number') {
      return Number.isInteger(v) ? v : v.toFixed(6);
    }
    return v;
  }).join(', ');
}

function formatDataForPython(data) {
  if (!Array.isArray(data)) return String(data);
  return data.map(v => {
    if (typeof v === 'number') {
      return Number.isInteger(v) ? v : v.toFixed(6);
    }
    return v;
  }).join(', ');
}

// ============================================================================
// EXPORT UTILITIES
// ============================================================================

/**
 * Download generated code as a file
 */
export function downloadCode(code, language, testType) {
  const extension = language === 'R' ? 'R' : 'py';
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `${testType.replace(/[^a-zA-Z0-9]/g, '_')}_${timestamp}.${extension}`;

  const blob = new Blob([code], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Copy code to clipboard
 */
export async function copyToClipboard(code) {
  try {
    await navigator.clipboard.writeText(code);
    return true;
  } catch (err) {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = code;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    try {
      document.execCommand('copy');
      document.body.removeChild(textarea);
      return true;
    } catch (e) {
      document.body.removeChild(textarea);
      return false;
    }
  }
}

const statisticalTestsCodeGenerator = {
  generateRCode,
  generatePythonCode,
  downloadCode,
  copyToClipboard
};

export default statisticalTestsCodeGenerator;
