# DOE Analysis Module Constants

# Design type constants
FACTORIAL_DESIGN = 'FACTORIAL'
FRACTIONAL_FACTORIAL_DESIGN = 'FRACTIONAL_FACTORIAL'
RESPONSE_SURFACE_DESIGN = 'RESPONSE_SURFACE'
CENTRAL_COMPOSITE_DESIGN = 'CENTRAL_COMPOSITE'
BOX_BEHNKEN_DESIGN = 'BOX_BEHNKEN'
PLACKETT_BURMAN_DESIGN = 'PLACKETT_BURMAN'
MIXTURE_DESIGN = 'MIXTURE'
DEFINITIVE_SCREENING_DESIGN = 'DEFINITIVE_SCREENING'
LATIN_SQUARE_DESIGN = 'LATIN_SQUARE'
SPLIT_PLOT_DESIGN = 'SPLIT_PLOT'
D_OPTIMAL_DESIGN = 'D_OPTIMAL'
CUSTOM_DESIGN = 'CUSTOM'

# Mapping between frontend and backend design types
DESIGN_TYPE_MAPPING = {
    'factorial': FACTORIAL_DESIGN,
    'fractional': FRACTIONAL_FACTORIAL_DESIGN,
    'response_surface': RESPONSE_SURFACE_DESIGN,
    'central-composite': CENTRAL_COMPOSITE_DESIGN,
    'box-behnken': BOX_BEHNKEN_DESIGN,
    'plackett-burman': PLACKETT_BURMAN_DESIGN,
    'mixture': MIXTURE_DESIGN,
    'definitive-screening': DEFINITIVE_SCREENING_DESIGN, 
    'latin-square': LATIN_SQUARE_DESIGN,
    'split-plot': SPLIT_PLOT_DESIGN,
    'd-optimal': D_OPTIMAL_DESIGN,
    'custom': CUSTOM_DESIGN,
}

# Reverse mapping for frontend display
DESIGN_TYPE_DISPLAY = {
    FACTORIAL_DESIGN: 'Full Factorial',
    FRACTIONAL_FACTORIAL_DESIGN: 'Fractional Factorial',
    RESPONSE_SURFACE_DESIGN: 'Response Surface',
    CENTRAL_COMPOSITE_DESIGN: 'Central Composite',
    BOX_BEHNKEN_DESIGN: 'Box-Behnken',
    PLACKETT_BURMAN_DESIGN: 'Plackett-Burman',
    MIXTURE_DESIGN: 'Mixture',
    DEFINITIVE_SCREENING_DESIGN: 'Definitive Screening',
    LATIN_SQUARE_DESIGN: 'Latin Square',
    SPLIT_PLOT_DESIGN: 'Split-Plot',
    D_OPTIMAL_DESIGN: 'D-Optimal',
    CUSTOM_DESIGN: 'Custom',
}

# Factor types
CONTINUOUS_FACTOR = 'CONTINUOUS'
CATEGORICAL_FACTOR = 'CATEGORICAL'

# Model types
LINEAR_MODEL = 'LINEAR'
QUADRATIC_MODEL = 'QUADRATIC'
INTERACTION_MODEL = 'INTERACTION'
CUSTOM_MODEL = 'CUSTOM'

# Term selection methods
MANUAL_SELECTION = 'MANUAL'
STEPWISE_SELECTION = 'STEPWISE'
BACKWARD_SELECTION = 'BACKWARD'
FORWARD_SELECTION = 'FORWARD'
ALL_TERMS = 'ALL_TERMS'

# Optimization methods
DESIRABILITY_METHOD = 'DESIRABILITY'
GRID_SEARCH_METHOD = 'GRID_SEARCH'
GENETIC_ALGORITHM_METHOD = 'GENETIC_ALGORITHM'
SIMULATED_ANNEALING_METHOD = 'SIMULATED_ANNEALING'

# Response goals
MAXIMIZE_GOAL = 'MAXIMIZE'
MINIMIZE_GOAL = 'MINIMIZE'
TARGET_GOAL = 'TARGET'
RANGE_GOAL = 'RANGE'
NONE_GOAL = 'NONE'

# Status codes
STATUS_PENDING = 'PENDING'
STATUS_PROCESSING = 'PROCESSING'
STATUS_COMPLETED = 'COMPLETED'
STATUS_FAILED = 'FAILED'
STATUS_CANCELLED = 'CANCELLED'