# Generated by Django 4.2.21 on 2025-05-12 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gene",
                "verbose_name_plural": "Genes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PCAProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scaling_method",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard (Z-score)"),
                            ("MINMAX", "Min-Max (0-1)"),
                            ("NONE", "None"),
                        ],
                        default="STANDARD",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pca_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PCA Project",
                "verbose_name_plural": "PCA Projects",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PCAResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("n_components", models.PositiveIntegerField(default=5)),
                (
                    "scaling_method",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard (Z-score)"),
                            ("MINMAX", "Min-Max (0-1)"),
                            ("NONE", "None"),
                        ],
                        default="STANDARD",
                        max_length=50,
                    ),
                ),
                ("explained_variance", models.JSONField(blank=True, null=True)),
                ("cumulative_variance", models.JSONField(blank=True, null=True)),
                ("loadings", models.JSONField(blank=True, null=True)),
                ("scores", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pca_results",
                        to="pca_analysis.pcaproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pca_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PCA Result",
                "verbose_name_plural": "PCA Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SampleGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_groups",
                        to="pca_analysis.pcaproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample Group",
                "verbose_name_plural": "Sample Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("replicate_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="pca_analysis.samplegroup",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="pca_analysis.pcaproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample",
                "verbose_name_plural": "Samples",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PCAVisualization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot_type",
                    models.CharField(
                        choices=[
                            ("2D", "2D Scatter Plot"),
                            ("3D", "3D Scatter Plot"),
                            ("BIPLOT", "Biplot"),
                            ("LOADINGS", "Loadings Plot"),
                        ],
                        default="2D",
                        max_length=20,
                    ),
                ),
                ("x_component", models.PositiveIntegerField(default=1)),
                ("y_component", models.PositiveIntegerField(default=2)),
                (
                    "z_component",
                    models.PositiveIntegerField(blank=True, default=3, null=True),
                ),
                ("color_palette", models.CharField(default="Set1", max_length=50)),
                ("marker_size", models.PositiveIntegerField(default=120)),
                ("show_confidence_ellipses", models.BooleanField(default=True)),
                ("ellipse_transparency", models.FloatField(default=0.15)),
                ("include_gene_loadings", models.BooleanField(default=True)),
                ("top_genes_count", models.PositiveIntegerField(default=10)),
                ("arrow_thickness", models.PositiveIntegerField(default=3)),
                (
                    "highlight_style",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("BOLD", "Bold"),
                            ("COLORFUL", "Colorful"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                ("pca_plot_image", models.TextField(blank=True)),
                ("loadings_plot_image", models.TextField(blank=True)),
                ("variance_plot_image", models.TextField(blank=True)),
                (
                    "pca_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="pca_analysis.pcaresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "PCA Visualization",
                "verbose_name_plural": "PCA Visualizations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pc1_contribution", models.FloatField()),
                ("pc2_contribution", models.FloatField()),
                ("total_contribution", models.FloatField()),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="pca_analysis.gene",
                    ),
                ),
                (
                    "pca_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_contributions",
                        to="pca_analysis.pcaresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gene Contribution",
                "verbose_name_plural": "Gene Contributions",
                "ordering": ["-total_contribution"],
            },
        ),
        migrations.AddField(
            model_name="gene",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genes",
                to="pca_analysis.pcaproject",
            ),
        ),
        migrations.CreateModel(
            name="ExpressionValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expression_values",
                        to="pca_analysis.gene",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expression_values",
                        to="pca_analysis.pcaproject",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expression_values",
                        to="pca_analysis.sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expression Value",
                "verbose_name_plural": "Expression Values",
                "unique_together": {("sample", "gene")},
            },
        ),
    ]
