# Generated by Django 4.2.21 on 2025-05-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pca_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gene",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pcaresult",
            name="group_centroids",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pcaresult",
            name="group_distances",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pcaresult",
            name="group_variations",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
