# Generated by Django 4.2.21 on 2025-05-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pca_analysis", "0002_gene_description_pcaresult_group_centroids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcaresult",
            name="name",
            field=models.CharField(default="PCA Analysis", max_length=255),
        ),
        migrations.AddField(
            model_name="pcaresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
