#!/usr/bin/env python3
"""
compute_kappa.py — inter-rater reliability + tool accuracy from the coded gold set.
====================================================================================

After the two coders fill `coder1_category` / `coder2_category` in `gold_set_coding_sheet.csv`
(optionally an `adjudicator_category` column for disagreements), this computes:
  1. Cohen's kappa between the two human coders (the pre-registered gate: kappa >= 0.6).
  2. The human CONSENSUS category per claim (agreement; else the adjudicator's call).
  3. The tool's accuracy vs that consensus for the headline "genuine inconsistency" flag:
     sensitivity, specificity, PPV, and a 4-category confusion matrix.

Writes KAPPA_REPORT.md and prints a summary. Pure stdlib.

Run:  python paper/census_paper/compute_kappa.py
"""
from __future__ import annotations

import csv
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
SHEET = HERE / "gold_set_coding_sheet.csv"
KEY = HERE / "gold_set_key.csv"
CATS = ["genuine", "one_tailed", "p_bound", "mis_extraction"]


def cohen_kappa(a: list, b: list) -> float:
    """Cohen's kappa for two raters over categorical labels (paired lists)."""
    n = len(a)
    if n == 0:
        return float("nan")
    po = sum(1 for x, y in zip(a, b) if x == y) / n
    ca, cb = Counter(a), Counter(b)
    pe = sum((ca.get(c, 0) / n) * (cb.get(c, 0) / n) for c in set(a) | set(b))
    return (po - pe) / (1 - pe) if pe < 1 else 1.0


def main() -> int:
    if not SHEET.exists() or not KEY.exists():
        raise SystemExit(f"need {SHEET.name} (coded) and {KEY.name}; run build_gold_set.py first.")
    rows = list(csv.DictReader(SHEET.open()))
    key = {r["idx"]: r["tool_category"] for r in csv.DictReader(KEY.open())}

    coder1, coder2, consensus, tool, skipped = [], [], [], [], 0
    for r in rows:
        c1 = (r.get("coder1_category") or "").strip().lower()
        c2 = (r.get("coder2_category") or "").strip().lower()
        adj = (r.get("adjudicator_category") or "").strip().lower()
        if c1 not in CATS or c2 not in CATS:
            skipped += 1
            continue
        coder1.append(c1)
        coder2.append(c2)
        if c1 == c2:
            consensus.append(c1)
        elif adj in CATS:
            consensus.append(adj)
        else:
            consensus.append(None)  # unresolved disagreement
        tool.append(key.get(r["idx"], "genuine"))

    n = len(coder1)
    if n == 0:
        raise SystemExit("no fully-coded rows yet — coders must fill coder1_category/coder2_category.")
    kappa = cohen_kappa(coder1, coder2)
    n_unresolved = sum(1 for c in consensus if c is None)

    # tool accuracy on the binary "genuine" flag, over rows with a resolved consensus
    tp = fp = fn = tn = 0
    confusion = defaultdict(int)  # (tool, human)
    for t, h in zip(tool, consensus):
        if h is None:
            continue
        confusion[(t, h)] += 1
        tg, hg = (t == "genuine"), (h == "genuine")
        tp += tg and hg
        fp += tg and not hg
        fn += (not tg) and hg
        tn += (not tg) and (not hg)
    sens = tp / (tp + fn) if (tp + fn) else float("nan")
    spec = tn / (tn + fp) if (tn + fp) else float("nan")
    ppv = tp / (tp + fp) if (tp + fp) else float("nan")

    lines = [
        "# Gold-set inter-rater reliability & tool accuracy",
        "",
        f"Fully-coded claims: **{n}** (skipped/uncoded: {skipped}; unresolved disagreements: {n_unresolved}).",
        "",
        "## 1. Human inter-rater reliability",
        f"- Cohen's kappa (coder1 vs coder2): **{kappa:.3f}**  "
        f"({'PASSES' if kappa >= 0.6 else 'BELOW'} the pre-registered threshold kappa >= 0.6).",
        f"- Raw agreement: {sum(1 for x, y in zip(coder1, coder2) if x == y)}/{n} "
        f"({100*sum(1 for x, y in zip(coder1, coder2) if x == y)/n:.1f}%).",
        "",
        "## 2. Tool accuracy vs human consensus — 'genuine inconsistency' flag",
        f"- TP={tp}  FP={fp}  FN={fn}  TN={tn}",
        f"- Sensitivity (recall): **{sens:.3f}**",
        f"- Specificity: **{spec:.3f}**",
        f"- PPV (precision): **{ppv:.3f}**",
        "",
        "## 3. Confusion matrix (tool rows × human-consensus cols)",
        "",
        "| tool \\ human | " + " | ".join(CATS) + " |",
        "|---|" + "|".join(["---"] * len(CATS)) + "|",
    ]
    for t in CATS:
        lines.append(f"| {t} | " + " | ".join(str(confusion.get((t, h), 0)) for h in CATS) + " |")
    lines += ["", "_Generated by compute_kappa.py. If kappa < 0.6, refine the codebook and re-code before "
              "using the gold set to calibrate the tool (PREREGISTRATION.md §6.3)._"]
    (HERE / "KAPPA_REPORT.md").write_text("\n".join(lines))

    print(f"kappa(coder1,coder2) = {kappa:.3f}  ({'PASS' if kappa >= 0.6 else 'BELOW 0.6'})")
    print(f"tool 'genuine' flag: sensitivity={sens:.3f}  specificity={spec:.3f}  PPV={ppv:.3f}  (n={n})")
    print(f"wrote {HERE / 'KAPPA_REPORT.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
