# Generated by Django 4.2.21 on 2025-05-12 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainapp", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "design_type",
                    models.CharField(
                        choices=[
                            ("FACTORIAL", "Factorial Design"),
                            ("FRACTIONAL_FACTORIAL", "Fractional Factorial Design"),
                            ("RESPONSE_SURFACE", "Response Surface Methodology"),
                            ("CENTRAL_COMPOSITE", "Central Composite Design"),
                            ("BOX_BEHNKEN", "Box-Behnken Design"),
                            ("PLACKETT_BURMAN", "Plackett-Burman Design"),
                            ("DEFINITIVE_SCREENING", "Definitive Screening Design"),
                            ("MIXTURE", "Mixture Design"),
                            ("LATIN_SQUARE", "Latin Square Design"),
                            ("SPLIT_PLOT", "Split-Plot Design"),
                            ("D_OPTIMAL", "D-Optimal Design"),
                            ("CUSTOM", "Custom Design"),
                        ],
                        max_length=30,
                    ),
                ),
                ("num_factors", models.IntegerField()),
                ("num_runs", models.IntegerField()),
                ("num_center_points", models.IntegerField(default=0)),
                ("num_replicates", models.IntegerField(default=1)),
                ("resolution", models.CharField(blank=True, max_length=10)),
                ("is_randomized", models.BooleanField(default=True)),
                ("block_column", models.CharField(blank=True, max_length=255)),
                ("num_blocks", models.IntegerField(default=1)),
                ("design_matrix", models.JSONField(default=dict)),
                ("factor_details", models.JSONField(default=dict)),
                ("response_details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_result",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_design_detail",
                        to="mainapp.analysisresult",
                    ),
                ),
                (
                    "analysis_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_designs",
                        to="mainapp.analysissession",
                    ),
                ),
            ],
            options={
                "verbose_name": "experiment design",
                "verbose_name_plural": "experiment designs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OptimizationAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "optimization_type",
                    models.CharField(
                        choices=[
                            ("single_response", "Single Response"),
                            ("multiple_response", "Multiple Response"),
                            ("desirability", "Desirability Function"),
                            ("pareto", "Pareto Optimization"),
                            ("custom", "Custom Optimization"),
                        ],
                        max_length=30,
                    ),
                ),
                ("criteria", models.JSONField(default=list)),
                ("weights", models.JSONField(default=dict)),
                ("optimal_settings", models.JSONField(default=dict)),
                ("predicted_responses", models.JSONField(default=dict)),
                ("desirability", models.FloatField(blank=True, null=True)),
                ("sensitivity_analysis", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_result",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimization_detail",
                        to="mainapp.analysisresult",
                    ),
                ),
                (
                    "experiment_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="optimizations",
                        to="doe_analysis.experimentdesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "optimization analysis",
                "verbose_name_plural": "optimization analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("response_name", models.CharField(max_length=255)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("linear", "Linear"),
                            ("interaction", "Interaction"),
                            ("quadratic", "Quadratic"),
                            ("cubic", "Cubic"),
                            ("reduced", "Reduced"),
                            ("customized", "Customized"),
                        ],
                        max_length=30,
                    ),
                ),
                ("r_squared", models.FloatField(blank=True, null=True)),
                ("adjusted_r_squared", models.FloatField(blank=True, null=True)),
                ("predicted_r_squared", models.FloatField(blank=True, null=True)),
                ("f_value", models.FloatField(blank=True, null=True)),
                ("p_value", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                ("aic", models.FloatField(blank=True, null=True)),
                ("bic", models.FloatField(blank=True, null=True)),
                ("terms", models.JSONField(default=list)),
                ("coefficients", models.JSONField(default=dict)),
                ("anova_results", models.JSONField(default=dict)),
                ("residual_analysis", models.JSONField(default=dict)),
                ("optimization_results", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_result",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_analysis_detail",
                        to="mainapp.analysisresult",
                    ),
                ),
                (
                    "experiment_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_analyses",
                        to="doe_analysis.experimentdesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "model analysis",
                "verbose_name_plural": "model analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResponseDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("units", models.CharField(blank=True, max_length=50)),
                (
                    "objective",
                    models.CharField(
                        choices=[
                            ("maximize", "Maximize"),
                            ("minimize", "Minimize"),
                            ("target", "Target Value"),
                            ("range", "In Range"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("lower_bound", models.FloatField(blank=True, null=True)),
                ("upper_bound", models.FloatField(blank=True, null=True)),
                ("importance", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="doe_analysis.experimentdesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "response definition",
                "verbose_name_plural": "response definitions",
                "unique_together": {("experiment_design", "name")},
            },
        ),
        migrations.CreateModel(
            name="FactorDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "factor_type",
                    models.CharField(
                        choices=[
                            ("CONTINUOUS", "Continuous"),
                            ("CATEGORICAL", "Categorical"),
                            ("MIXTURE_COMPONENT", "Mixture Component"),
                        ],
                        max_length=20,
                    ),
                ),
                ("low_level", models.FloatField(blank=True, null=True)),
                ("high_level", models.FloatField(blank=True, null=True)),
                ("center_point", models.FloatField(blank=True, null=True)),
                ("level_values", models.JSONField(blank=True, default=list)),
                ("units", models.CharField(blank=True, max_length=50)),
                ("min_constraint", models.FloatField(blank=True, null=True)),
                ("max_constraint", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factors",
                        to="doe_analysis.experimentdesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "factor definition",
                "verbose_name_plural": "factor definitions",
                "unique_together": {("experiment_design", "name")},
            },
        ),
        migrations.CreateModel(
            name="ExperimentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("run_order", models.IntegerField()),
                ("standard_order", models.IntegerField()),
                ("block", models.IntegerField(default=1)),
                ("is_center_point", models.BooleanField(default=False)),
                ("factor_values", models.JSONField(default=dict)),
                ("response_values", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("excluded", "Excluded from Analysis"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "experiment_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="doe_analysis.experimentdesign",
                    ),
                ),
            ],
            options={
                "verbose_name": "experiment run",
                "verbose_name_plural": "experiment runs",
                "ordering": ["experiment_design", "run_order"],
                "unique_together": {("experiment_design", "run_order")},
            },
        ),
    ]
