# Generated by Django 4.2.21 on 2025-05-12 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("BINOMIAL", "Binomial"),
                            ("POISSON", "Poisson"),
                            ("NORMAL", "Normal"),
                            ("EXPONENTIAL", "Exponential"),
                            ("UNIFORM", "Uniform"),
                            ("GAMMA", "Gamma"),
                            ("BETA", "Beta"),
                            ("CHI_SQUARED", "Chi-squared"),
                            ("T", "Student's t"),
                            ("F", "F-distribution"),
                            ("LOG_NORMAL", "Log-normal"),
                            ("WEIBULL", "Weibull"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DISCRETE", "Discrete"),
                            ("CONTINUOUS", "Continuous"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DistributionVisualization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visualization_type",
                    models.CharField(
                        choices=[
                            ("PDF", "Probability Density Function"),
                            ("PMF", "Probability Mass Function"),
                            ("CDF", "Cumulative Distribution Function"),
                            ("QUANTILE", "Quantile Function"),
                            ("HISTOGRAM", "Histogram"),
                            ("BOX_PLOT", "Box Plot"),
                            ("PP_PLOT", "P-P Plot"),
                            ("QQ_PLOT", "Q-Q Plot"),
                        ],
                        max_length=20,
                    ),
                ),
                ("settings", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="probability_distributions.distribution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionFitting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parameters", models.JSONField()),
                ("goodness_of_fit", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fittings",
                        to="probability_distributions.dataset",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fittings",
                        to="probability_distributions.distribution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("comparison_type", models.CharField(max_length=50)),
                ("settings", models.JSONField()),
                ("results", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "distributions",
                    models.ManyToManyField(
                        related_name="comparisons",
                        to="probability_distributions.distribution",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons",
                        to="probability_distributions.distributionproject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="distribution",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to="probability_distributions.distributionproject",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="probability_distributions.distributionproject",
            ),
        ),
        migrations.CreateModel(
            name="BinomialApproximation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("n", models.IntegerField()),
                ("p", models.FloatField()),
                ("approximation_types", models.JSONField()),
                ("results", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approximations",
                        to="probability_distributions.distributionproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationSimulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("EMAIL_ARRIVALS", "Email Arrivals (Poisson)"),
                            ("QUALITY_CONTROL", "Quality Control (Normal)"),
                            (
                                "CLINICAL_TRIALS",
                                "Clinical Trials (Binomial and Normal)",
                            ),
                            ("NETWORK_TRAFFIC", "Network Traffic (Poisson)"),
                            (
                                "MANUFACTURING_DEFECTS",
                                "Manufacturing Defects (Binomial and Poisson)",
                            ),
                            ("CUSTOM", "Custom Simulation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("parameters", models.JSONField()),
                ("results", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulations",
                        to="probability_distributions.distributionproject",
                    ),
                ),
            ],
        ),
    ]
