# Generated by Django 4.2.10 on 2026-02-19 12:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_analysissession_analysisresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("issn", models.CharField(blank=True, max_length=20)),
                ("eissn", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("psychology", "Psychology"),
                            ("medicine", "Medicine"),
                            ("economics", "Economics"),
                            ("education", "Education"),
                            ("biology", "Biology"),
                            ("social_science", "Social Science"),
                            ("clinical_trials", "Clinical Trials"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                (
                    "review_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Journal-specific review settings: {"min_sqs_score": 60, "require_effect_sizes": true, "require_power_analysis": false, "severity_threshold": "major"}',
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, help_text="URL for report delivery callbacks"
                    ),
                ),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ManuscriptSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "manuscript_id",
                    models.CharField(
                        blank=True,
                        help_text="Journal's internal manuscript ID",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("authors", models.JSONField(blank=True, default=list)),
                ("abstract", models.TextField(blank=True)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("tex", "LaTeX"),
                            ("docx", "DOCX"),
                            ("txt", "Plain Text"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_size_bytes", models.IntegerField(default=0)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, help_text="SHA-256 of uploaded file", max_length=128
                    ),
                ),
                ("word_count", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("parsing", "Parsing"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "sqs_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("sqs_grade", models.CharField(blank=True, max_length=5)),
                ("claims_found", models.IntegerField(default=0)),
                ("claims_consistent", models.IntegerField(default=0)),
                ("claims_inconsistent", models.IntegerField(default=0)),
                (
                    "consistency_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("decision_errors", models.IntegerField(default=0)),
                ("gross_errors", models.IntegerField(default=0)),
                ("parse_result", models.JSONField(blank=True, default=dict)),
                ("claim_data", models.JSONField(blank=True, default=dict)),
                ("consistency_data", models.JSONField(blank=True, default=dict)),
                ("sqs_data", models.JSONField(blank=True, default=dict)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Journal that submitted this (null for direct uploads)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="core.journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manuscript Submission",
                "verbose_name_plural": "Manuscript Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 chars for identification", max_length=8
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="SHA-256 hash of full key", max_length=128
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this key", max_length=100
                    ),
                ),
                ("can_submit", models.BooleanField(default=True)),
                ("can_batch_submit", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=False)),
                ("rate_limit_per_hour", models.IntegerField(default=60)),
                ("rate_limit_per_day", models.IntegerField(default=500)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="core.journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal API Key",
                "verbose_name_plural": "Journal API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("editor", "Editor Report"),
                            ("reviewer", "Reviewer Report"),
                            ("author", "Author Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Executive summary of findings"),
                ),
                (
                    "overall_assessment",
                    models.CharField(
                        choices=[
                            ("pass", "Pass — No significant issues"),
                            ("minor_issues", "Minor Issues — Requires minor revisions"),
                            ("major_issues", "Major Issues — Requires major revisions"),
                            ("critical", "Critical — Fundamental statistical concerns"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        default=list,
                        help_text='List of findings: [{"severity": "major", "category": "consistency", "title": "...", "description": "...", "evidence": "...", "recommendation": "..."}]',
                    ),
                ),
                (
                    "positive_findings",
                    models.JSONField(
                        default=list, help_text="Good practices identified"
                    ),
                ),
                (
                    "sqs_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "consistency_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("methodology_assessment", models.TextField(blank=True)),
                ("statistical_claims_review", models.TextField(blank=True)),
                ("reporting_quality", models.TextField(blank=True)),
                ("recommendations", models.JSONField(default=list)),
                ("delivered", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("api", "API Response"),
                            ("webhook", "Webhook"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.manuscriptsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Report",
                "verbose_name_plural": "Review Reports",
                "ordering": ["-created_at"],
                "unique_together": {("submission", "report_type")},
            },
        ),
        migrations.AddIndex(
            model_name="manuscriptsubmission",
            index=models.Index(
                fields=["-submitted_at", "status"],
                name="core_manusc_submitt_5f7b1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="manuscriptsubmission",
            index=models.Index(
                fields=["journal", "-submitted_at"],
                name="core_manusc_journal_47f7bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="manuscriptsubmission",
            index=models.Index(
                fields=["manuscript_id"], name="core_manusc_manuscr_35445c_idx"
            ),
        ),
    ]
