# Generated by Django 4.2.10 on 2026-02-19 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_journal_manuscriptsubmission_journalapikey_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"default_alpha": 0.05, "default_field": "general", "require_guardian": true, "allow_expert_mode": false}',
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                (
                    "primary_color",
                    models.CharField(blank=True, help_text="Hex color e.g. #1976d2", max_length=7),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Descriptive name for this key", max_length=100),
                ),
                (
                    "key_prefix",
                    models.CharField(help_text="First 8 chars for identification", max_length=8),
                ),
                (
                    "key_hash",
                    models.CharField(help_text="SHA-256 hash of full key", max_length=128),
                ),
                (
                    "scopes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["stats:read", "stats:write", "autonomous:read", "autonomous:write", "manuscript:read", "manuscript:write", "platform:read"]',
                    ),
                ),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("rate_limit_per_day", models.IntegerField(default=10000)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform API Key",
                "verbose_name_plural": "Platform API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "price_monthly_cents",
                    models.IntegerField(default=0, help_text="Monthly price in cents (0=free)"),
                ),
                (
                    "price_yearly_cents",
                    models.IntegerField(default=0, help_text="Yearly price in cents (discount)"),
                ),
                (
                    "stripe_price_id_monthly",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "stripe_price_id_yearly",
                    models.CharField(blank=True, max_length=100),
                ),
                ("max_analyses_per_month", models.IntegerField(default=100)),
                ("max_upload_size_mb", models.IntegerField(default=10)),
                ("max_projects", models.IntegerField(default=5)),
                ("max_team_members", models.IntegerField(default=1)),
                ("max_api_keys", models.IntegerField(default=1)),
                ("max_stored_datasets", models.IntegerField(default=10)),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"guardian": true, "autonomous": true, "manuscript_review": false, "ai_advisor": false, "export_pdf": true, "priority_support": false, "sso": false, "rbac": false, "audit_log": false, "api_access": false, "custom_branding": false, "dedicated_support": false}',
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Default tier for new orgs"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Tier",
                "verbose_name_plural": "Subscription Tiers",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organizations",
                to="core.subscriptiontier",
            ),
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(db_index=True, max_length=255)),
                ("method", models.CharField(max_length=10)),
                (
                    "endpoint_category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="stats, power, autonomous, manuscript, platform, etc.",
                        max_length=50,
                    ),
                ),
                ("status_code", models.IntegerField()),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("response_size_bytes", models.IntegerField(blank=True, null=True)),
                (
                    "client_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("web", "Web App"),
                            ("sdk_python", "Python SDK"),
                            ("sdk_r", "R SDK"),
                            ("cli", "CLI"),
                            ("api", "Direct API"),
                            ("journal", "Journal Integration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("is_billable", models.BooleanField(default=True)),
                ("credits_consumed", models.IntegerField(default=1)),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="core.platformapikey",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Record",
                "verbose_name_plural": "Usage Records",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-timestamp"],
                        name="core_usager_organiz_bad0e7_idx",
                    ),
                    models.Index(
                        fields=["organization", "endpoint_category", "-timestamp"],
                        name="core_usager_organiz_6fca6f_idx",
                    ),
                    models.Index(
                        fields=["-timestamp", "status_code"],
                        name="core_usager_timesta_ddf306_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("invitation_email", models.EmailField(blank=True, max_length=254)),
                ("invitation_accepted", models.BooleanField(default=True)),
                ("invitation_token", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "ordering": ["role", "joined_at"],
                "unique_together": {("organization", "user")},
            },
        ),
    ]
