# Generated by Django 4.2.10 on 2026-02-19 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_project_consentrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("plugin_type", models.CharField(choices=[("statistical_test", "Statistical Test"), ("sqs_rule_pack", "SQS Rule Pack"), ("visualization", "Visualization Template"), ("data_connector", "Data Connector"), ("report_template", "Report Template")], max_length=30)),
                ("description", models.TextField()),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("author_name", models.CharField(max_length=200)),
                ("author_email", models.EmailField(blank=True, max_length=254)),
                ("homepage_url", models.URLField(blank=True)),
                ("repository_url", models.URLField(blank=True)),
                ("icon_url", models.URLField(blank=True)),
                ("config_schema", models.JSONField(blank=True, default=dict, help_text="JSON Schema for plugin configuration")),
                ("entry_point", models.JSONField(default=dict, help_text="Plugin entry point definition")),
                ("dependencies", models.JSONField(blank=True, default=list)),
                ("is_official", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("rating_sum", models.PositiveIntegerField(default=0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plugin",
                "ordering": ["-downloads"],
            },
        ),
        migrations.CreateModel(
            name="PluginInstallation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("installed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("installed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="installed_plugins", to="core.organization")),
                ("plugin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="installations", to="core.plugin")),
            ],
            options={
                "ordering": ["-installed_at"],
                "unique_together": {("plugin", "organization")},
            },
        ),
        migrations.CreateModel(
            name="PluginReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rating", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("plugin", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="core.plugin")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("plugin", "user")},
            },
        ),
    ]
