# Generated by Django 4.2.10 on 2026-05-06 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_plugin_marketplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="LTINonceUsed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issuer", models.CharField(db_index=True, max_length=512)),
                ("nonce", models.CharField(max_length=512)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "LTI Nonce (used)",
                "verbose_name_plural": "LTI Nonces (used)",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="core_ltinon_expires_0c28b8_idx"
                    )
                ],
                "unique_together": {("issuer", "nonce")},
            },
        ),
    ]
