# Generated by Django 4.2.10 on 2026-05-06 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_add_lti_nonce_used"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationExamAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("foundations", "Foundations"),
                            ("practitioner", "Practitioner"),
                            ("expert", "Expert"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("question_ids", models.JSONField(default=list)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cert_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification Exam Attempt",
                "verbose_name_plural": "Certification Exam Attempts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificationQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("foundations", "Foundations"),
                            ("practitioner", "Practitioner"),
                            ("expert", "Expert"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_index", models.PositiveSmallIntegerField()),
                ("explanation", models.TextField(blank=True)),
                ("topic", models.CharField(db_index=True, max_length=128)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Certification Question",
                "verbose_name_plural": "Certification Questions",
                "ordering": ["level", "topic", "id"],
            },
        ),
        migrations.CreateModel(
            name="CertificationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("foundations", "Foundations"),
                            ("practitioner", "Practitioner"),
                            ("expert", "Expert"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "certificate_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("signature", models.CharField(max_length=128)),
                ("score", models.FloatField()),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("is_revoked", models.BooleanField(db_index=True, default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.CharField(blank=True, max_length=256)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="core.certificationexamattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cert_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification Record",
                "verbose_name_plural": "Certification Records",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "level"], name="core_certif_user_id_29814b_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_certif_expires_f0a268_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="certificationexamattempt",
            index=models.Index(
                fields=["user", "level"], name="core_certif_user_id_fb97a9_idx"
            ),
        ),
    ]
