# Generated by Django 4.2.10 on 2026-05-06 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_seed_certification_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "license_key",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("institution_name", models.CharField(max_length=256)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("department", "Department"),
                            ("school", "School/College"),
                            ("university", "University-Wide"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("admin_email", models.EmailField(max_length=254)),
                ("domain", models.CharField(max_length=255)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("email_domain", "Email Domain"),
                            ("ip_range", "IP Range"),
                            ("saml_sso", "SAML SSO"),
                            ("manual", "Manual"),
                        ],
                        default="email_domain",
                        max_length=32,
                    ),
                ),
                ("max_users", models.IntegerField()),
                ("max_analyses_per_month", models.IntegerField()),
                ("features", models.JSONField(default=list)),
                ("price_yearly", models.IntegerField(default=0)),
                ("duration_years", models.PositiveSmallIntegerField(default=1)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Site License",
                "verbose_name_plural": "Site Licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteLicenseUsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_email", models.EmailField(db_index=True, max_length=254)),
                ("feature", models.CharField(db_index=True, max_length=64)),
                ("analysis_type", models.CharField(blank=True, max_length=64)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="core.sitelicense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site License Usage Record",
                "verbose_name_plural": "Site License Usage Records",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sitelicense",
            index=models.Index(fields=["domain"], name="core_siteli_domain_eab22b_idx"),
        ),
        migrations.AddIndex(
            model_name="sitelicenseusagerecord",
            index=models.Index(
                fields=["license", "occurred_at"], name="core_siteli_license_f7c526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitelicenseusagerecord",
            index=models.Index(
                fields=["license", "feature"], name="core_siteli_license_268196_idx"
            ),
        ),
    ]
