# Generated by Django 4.2.10 on 2026-05-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_add_site_license_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscriptsubmission",
            name="report_token_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="SHA-256 of the report share token (raw token never stored)",
                max_length=128,
            ),
        ),
    ]
