# Generated by Django 4.2.10 on 2026-06-02 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_manuscriptsubmission_report_token_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReproducibilityReceipt",
            fields=[
                (
                    "receipt_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(default="sfs-receipt/1.0", max_length=32),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[
                            ("manuscript", "Manuscript verification"),
                            ("analysis", "Analysis run"),
                        ],
                        db_index=True,
                        default="manuscript",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "subject_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of the artifact attested (paper file_hash / dataset fingerprint)",
                        max_length=128,
                    ),
                ),
                (
                    "canonical_payload_hash",
                    models.CharField(
                        help_text="SHA-256 of the canonical JSON body that was signed",
                        max_length=128,
                    ),
                ),
                ("sig_alg", models.CharField(default="RS256", max_length=16)),
                ("key_id", models.CharField(blank=True, max_length=128)),
                (
                    "signature",
                    models.TextField(
                        help_text="base64 detached RS256 signature over the canonical body bytes"
                    ),
                ),
                (
                    "receipt_json",
                    models.JSONField(
                        default=dict,
                        help_text="The exact canonical receipt body that was signed",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.CharField(blank=True, max_length=255)),
                (
                    "report_token_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA-256 of the receipt download token (raw token never stored)",
                        max_length=128,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="core.manuscriptsubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reproducibility_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reproducibility Receipt",
                "verbose_name_plural": "Reproducibility Receipts",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["-issued_at", "receipt_type"],
                        name="core_reprod_issued__b9d9f5_idx",
                    ),
                    models.Index(
                        fields=["subject_hash"], name="core_reprod_subject_dfde45_idx"
                    ),
                ],
            },
        ),
    ]
