# Generated by Django 4.2.30 on 2026-06-25 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_reproducibilityreceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 of the uploaded manuscript",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("n_claims", models.IntegerField(default=0)),
                (
                    "verifiability_rate",
                    models.FloatField(
                        blank=True,
                        help_text="fraction of claims actually attempted (VERIFIED + DISCREPANT + ASSUMPTION_VIOLATED)",
                        null=True,
                    ),
                ),
                (
                    "coverage",
                    models.FloatField(
                        blank=True,
                        help_text="extraction coverage (claims_with_p / candidate p-mentions)",
                        null=True,
                    ),
                ),
                ("low_coverage", models.BooleanField(default=False)),
                (
                    "n_inconsistent_reporting",
                    models.IntegerField(
                        default=0, help_text="secondary statcheck signal count"
                    ),
                ),
                ("verdict_distribution", models.JSONField(blank=True, default=dict)),
                ("certify_note", models.TextField(blank=True)),
                ("profile_data", models.JSONField(blank=True, default=dict)),
                (
                    "data_source",
                    models.CharField(
                        blank=True,
                        default="none",
                        help_text="e.g. 'none', 'uploaded_table', 'geo:GSE271517'",
                        max_length=255,
                    ),
                ),
                (
                    "report_token_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="SHA-256 of the report share token (raw token never stored)",
                        max_length=128,
                    ),
                ),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Run",
                "verbose_name_plural": "Verification Runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at", "status"],
                        name="core_verifi_created_3cd076_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LinkedDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded table"),
                            ("geo", "GEO"),
                            ("dryad", "Dryad"),
                            ("zenodo", "Zenodo"),
                            ("figshare", "figshare"),
                            ("osf", "OSF"),
                            ("other", "Other"),
                        ],
                        default="uploaded",
                        max_length=32,
                    ),
                ),
                ("accession", models.CharField(blank=True, max_length=128)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("n_rows", models.IntegerField(blank=True, null=True)),
                ("n_cols", models.IntegerField(blank=True, null=True)),
                (
                    "link_status",
                    models.CharField(
                        choices=[
                            ("linked", "Linked"),
                            ("ambiguous", "Ambiguous"),
                            ("unlinkable", "Unlinkable"),
                            ("fetched", "Fetched"),
                            ("fetch_failed", "Fetch failed"),
                        ],
                        default="linked",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="core.verificationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linked Dataset",
                "verbose_name_plural": "Linked Datasets",
                "ordering": ["run", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClaimVerdictRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_id", models.CharField(max_length=32)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("DISCREPANT", "Discrepant"),
                            ("ASSUMPTION_VIOLATED", "Assumption violated"),
                            ("ASSUMPTION_UNREPORTED", "Assumption unreported"),
                            ("INSUFFICIENT_DATA", "Insufficient data"),
                            ("UNVERIFIABLE_EXTRACTION", "Unverifiable extraction"),
                            ("INCONSISTENT_REPORTING", "Inconsistent reporting"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("claim_text", models.TextField(blank=True)),
                ("test_name", models.CharField(blank=True, max_length=64)),
                ("claimed_statistic", models.FloatField(blank=True, null=True)),
                ("claimed_p_value", models.FloatField(blank=True, null=True)),
                ("recomputed_statistic", models.FloatField(blank=True, null=True)),
                ("recomputed_p_value", models.FloatField(blank=True, null=True)),
                ("data_available", models.BooleanField(default=False)),
                ("assumptions_satisfied", models.BooleanField(blank=True, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_verdicts",
                        to="core.verificationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claim Verdict Record",
                "verbose_name_plural": "Claim Verdict Records",
                "ordering": ["run", "claim_id"],
                "indexes": [
                    models.Index(
                        fields=["run", "verdict"], name="core_claimv_run_id_cabd85_idx"
                    )
                ],
            },
        ),
    ]
