# Generated by Django 4.2.30 on 2026-06-27 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_verificationrun_linkeddataset_claimverdictrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaimDatasetLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cited_reference", models.CharField(blank=True, max_length=128)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "reference-directed",
                                "Reference-directed (author's citation selected the file)",
                            ),
                            (
                                "conflict",
                                "Citation-content conflict (cited file didn't match; another did)",
                            ),
                            (
                                "content",
                                "Content match (no citation; matched by columns)",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("auto_linked", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Claim-Dataset Link",
                "verbose_name_plural": "Claim-Dataset Links",
                "ordering": ["claim", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="claimverdictrecord",
            name="cited_references",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="claimverdictrecord",
            name="link_method",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="claimverdictrecord",
            name="resolution_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claimverdictrecord",
            name="resolved_reference",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="claimverdictrecord",
            name="section",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="claimverdictrecord",
            name="source_file",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="claimverdictrecord",
            index=models.Index(
                fields=["run", "link_method"], name="core_claimv_run_id_dcb10d_idx"
            ),
        ),
        migrations.AddField(
            model_name="claimdatasetlink",
            name="claim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dataset_links",
                to="core.claimverdictrecord",
            ),
        ),
        migrations.AddField(
            model_name="claimdatasetlink",
            name="dataset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claim_links",
                to="core.linkeddataset",
            ),
        ),
        migrations.AddIndex(
            model_name="claimdatasetlink",
            index=models.Index(fields=["method"], name="core_claimd_method_f7f5f6_idx"),
        ),
    ]
